// ISO 3166-1 alpha-2 → { fr, en, ar }
const NAMES = {
  AF: { fr: 'Afghanistan',          en: 'Afghanistan',          ar: 'أفغانستان' },
  DZ: { fr: 'Algérie',              en: 'Algeria',              ar: 'الجزائر' },
  DE: { fr: 'Allemagne',            en: 'Germany',              ar: 'ألمانيا' },
  AO: { fr: 'Angola',               en: 'Angola',               ar: 'أنغولا' },
  SA: { fr: 'Arabie Saoudite',      en: 'Saudi Arabia',         ar: 'المملكة العربية السعودية' },
  AR: { fr: 'Argentine',            en: 'Argentina',            ar: 'الأرجنتين' },
  AU: { fr: 'Australie',            en: 'Australia',            ar: 'أستراليا' },
  AT: { fr: 'Autriche',             en: 'Austria',              ar: 'النمسا' },
  AZ: { fr: 'Azerbaïdjan',          en: 'Azerbaijan',           ar: 'أذربيجان' },
  BH: { fr: 'Bahreïn',              en: 'Bahrain',              ar: 'البحرين' },
  BD: { fr: 'Bangladesh',           en: 'Bangladesh',           ar: 'بنغلاديش' },
  BE: { fr: 'Belgique',             en: 'Belgium',              ar: 'بلجيكا' },
  BJ: { fr: 'Bénin',                en: 'Benin',                ar: 'بنين' },
  MM: { fr: 'Birmanie',             en: 'Myanmar',              ar: 'ميانمار' },
  BA: { fr: 'Bosnie-Herzégovine',   en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  BG: { fr: 'Bulgarie',             en: 'Bulgaria',             ar: 'بلغاريا' },
  BF: { fr: 'Burkina Faso',         en: 'Burkina Faso',         ar: 'بوركينا فاسو' },
  BI: { fr: 'Burundi',              en: 'Burundi',              ar: 'بوروندي' },
  KH: { fr: 'Cambodge',             en: 'Cambodia',             ar: 'كمبوديا' },
  CM: { fr: 'Cameroun',             en: 'Cameroon',             ar: 'الكاميرون' },
  CA: { fr: 'Canada',               en: 'Canada',               ar: 'كندا' },
  CF: { fr: 'Centrafrique',         en: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى' },
  KM: { fr: 'Comores',              en: 'Comoros',              ar: 'جزر القمر' },
  CG: { fr: 'Congo',                en: 'Republic of the Congo', ar: 'الكونغو' },
  CD: { fr: 'RD Congo',             en: 'DR Congo',             ar: 'الكونغو الديمقراطية' },
  CI: { fr: "Côte d'Ivoire",        en: "Côte d'Ivoire",        ar: 'ساحل العاج' },
  DK: { fr: 'Danemark',             en: 'Denmark',              ar: 'الدنمارك' },
  DJ: { fr: 'Djibouti',             en: 'Djibouti',             ar: 'جيبوتي' },
  EG: { fr: 'Égypte',               en: 'Egypt',                ar: 'مصر' },
  AE: { fr: 'Émirats arabes unis',  en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' },
  ES: { fr: 'Espagne',              en: 'Spain',                ar: 'إسبانيا' },
  ET: { fr: 'Éthiopie',             en: 'Ethiopia',             ar: 'إثيوبيا' },
  FI: { fr: 'Finlande',             en: 'Finland',              ar: 'فنلندا' },
  FR: { fr: 'France',               en: 'France',               ar: 'فرنسا' },
  GA: { fr: 'Gabon',                en: 'Gabon',                ar: 'الغابون' },
  GM: { fr: 'Gambie',               en: 'Gambia',               ar: 'غامبيا' },
  GH: { fr: 'Ghana',                en: 'Ghana',                ar: 'غانا' },
  GR: { fr: 'Grèce',                en: 'Greece',               ar: 'اليونان' },
  GN: { fr: 'Guinée',               en: 'Guinea',               ar: 'غينيا' },
  GW: { fr: 'Guinée-Bissau',        en: 'Guinea-Bissau',        ar: 'غينيا بيساو' },
  GQ: { fr: 'Guinée équatoriale',   en: 'Equatorial Guinea',    ar: 'غينيا الاستوائية' },
  IN: { fr: 'Inde',                  en: 'India',                ar: 'الهند' },
  ID: { fr: 'Indonésie',            en: 'Indonesia',            ar: 'إندونيسيا' },
  IQ: { fr: 'Irak',                 en: 'Iraq',                 ar: 'العراق' },
  IR: { fr: 'Iran',                  en: 'Iran',                 ar: 'إيران' },
  IE: { fr: 'Irlande',              en: 'Ireland',              ar: 'أيرلندا' },
  IT: { fr: 'Italie',               en: 'Italy',                ar: 'إيطاليا' },
  JO: { fr: 'Jordanie',             en: 'Jordan',               ar: 'الأردن' },
  KZ: { fr: 'Kazakhstan',           en: 'Kazakhstan',           ar: 'كازاخستان' },
  KE: { fr: 'Kenya',                en: 'Kenya',                ar: 'كينيا' },
  KG: { fr: 'Kirghizistan',         en: 'Kyrgyzstan',           ar: 'قيرغيزستان' },
  KW: { fr: 'Koweït',               en: 'Kuwait',               ar: 'الكويت' },
  LB: { fr: 'Liban',                en: 'Lebanon',              ar: 'لبنان' },
  LY: { fr: 'Libye',                en: 'Libya',                ar: 'ليبيا' },
  LU: { fr: 'Luxembourg',           en: 'Luxembourg',           ar: 'لوكسمبورغ' },
  MK: { fr: 'Macédoine du Nord',    en: 'North Macedonia',      ar: 'مقدونيا الشمالية' },
  MG: { fr: 'Madagascar',           en: 'Madagascar',           ar: 'مدغشقر' },
  MY: { fr: 'Malaisie',             en: 'Malaysia',             ar: 'ماليزيا' },
  ML: { fr: 'Mali',                  en: 'Mali',                 ar: 'مالي' },
  MA: { fr: 'Maroc',                en: 'Morocco',              ar: 'المغرب' },
  MR: { fr: 'Mauritanie',           en: 'Mauritania',           ar: 'موريتانيا' },
  MX: { fr: 'Mexique',              en: 'Mexico',               ar: 'المكسيك' },
  MD: { fr: 'Moldavie',             en: 'Moldova',              ar: 'مولدوفا' },
  MZ: { fr: 'Mozambique',           en: 'Mozambique',           ar: 'موزمبيق' },
  NA: { fr: 'Namibie',              en: 'Namibia',              ar: 'ناميبيا' },
  NE: { fr: 'Niger',                en: 'Niger',                ar: 'النيجر' },
  NG: { fr: 'Nigéria',              en: 'Nigeria',              ar: 'نيجيريا' },
  NO: { fr: 'Norvège',              en: 'Norway',               ar: 'النرويج' },
  NL: { fr: 'Pays-Bas',             en: 'Netherlands',          ar: 'هولندا' },
  PK: { fr: 'Pakistan',             en: 'Pakistan',             ar: 'باكستان' },
  PS: { fr: 'Palestine',            en: 'Palestine',            ar: 'فلسطين' },
  PH: { fr: 'Philippines',          en: 'Philippines',          ar: 'الفلبين' },
  PL: { fr: 'Pologne',              en: 'Poland',               ar: 'بولندا' },
  PT: { fr: 'Portugal',             en: 'Portugal',             ar: 'البرتغال' },
  QA: { fr: 'Qatar',                en: 'Qatar',                ar: 'قطر' },
  RO: { fr: 'Roumanie',             en: 'Romania',              ar: 'رومانيا' },
  GB: { fr: 'Royaume-Uni',          en: 'United Kingdom',       ar: 'المملكة المتحدة' },
  RW: { fr: 'Rwanda',               en: 'Rwanda',               ar: 'رواندا' },
  SN: { fr: 'Sénégal',              en: 'Senegal',              ar: 'السنغال' },
  SL: { fr: 'Sierra Leone',         en: 'Sierra Leone',         ar: 'سيراليون' },
  SG: { fr: 'Singapour',            en: 'Singapore',            ar: 'سنغافورة' },
  SO: { fr: 'Somalie',              en: 'Somalia',              ar: 'الصومال' },
  SD: { fr: 'Soudan',               en: 'Sudan',                ar: 'السودان' },
  ZA: { fr: 'Afrique du Sud',       en: 'South Africa',         ar: 'جنوب أفريقيا' },
  SE: { fr: 'Suède',                en: 'Sweden',               ar: 'السويد' },
  CH: { fr: 'Suisse',               en: 'Switzerland',          ar: 'سويسرا' },
  SY: { fr: 'Syrie',                en: 'Syria',                ar: 'سوريا' },
  TJ: { fr: 'Tadjikistan',          en: 'Tajikistan',           ar: 'طاجيكستان' },
  TZ: { fr: 'Tanzanie',             en: 'Tanzania',             ar: 'تنزانيا' },
  TD: { fr: 'Tchad',                en: 'Chad',                 ar: 'تشاد' },
  TG: { fr: 'Togo',                 en: 'Togo',                 ar: 'توغو' },
  TN: { fr: 'Tunisie',              en: 'Tunisia',              ar: 'تونس' },
  TM: { fr: 'Turkménistan',         en: 'Turkmenistan',         ar: 'تركمانستان' },
  TR: { fr: 'Turquie',              en: 'Turkey',               ar: 'تركيا' },
  UG: { fr: 'Ouganda',              en: 'Uganda',               ar: 'أوغندا' },
  UA: { fr: 'Ukraine',              en: 'Ukraine',              ar: 'أوكرانيا' },
  UZ: { fr: 'Ouzbékistan',          en: 'Uzbekistan',           ar: 'أوزبكستان' },
  YE: { fr: 'Yémen',                en: 'Yemen',                ar: 'اليمن' },
  ZM: { fr: 'Zambie',               en: 'Zambia',               ar: 'زامبيا' },
  ZW: { fr: 'Zimbabwe',             en: 'Zimbabwe',             ar: 'زيمبابوي' },
  US: { fr: 'États-Unis',           en: 'United States',        ar: 'الولايات المتحدة' },
  OM: { fr: 'Oman',                  en: 'Oman',                 ar: 'عُمان' },
  CN: { fr: 'Chine',                          en: 'China',                          ar: 'الصين' },
  JP: { fr: 'Japon',                          en: 'Japan',                          ar: 'اليابان' },
  KR: { fr: 'Corée du Sud',                   en: 'South Korea',                    ar: 'كوريا الجنوبية' },
  TH: { fr: 'Thaïlande',                      en: 'Thailand',                       ar: 'تايلاند' },
  VN: { fr: 'Vietnam',                        en: 'Vietnam',                        ar: 'فيتنام' },
  // Europe
  AL: { fr: 'Albanie',                        en: 'Albania',                        ar: 'ألبانيا' },
  AD: { fr: 'Andorre',                        en: 'Andorra',                        ar: 'أندورا' },
  AM: { fr: 'Arménie',                        en: 'Armenia',                        ar: 'أرمينيا' },
  BY: { fr: 'Biélorussie',                    en: 'Belarus',                        ar: 'بيلاروس' },
  CY: { fr: 'Chypre',                         en: 'Cyprus',                         ar: 'قبرص' },
  HR: { fr: 'Croatie',                        en: 'Croatia',                        ar: 'كرواتيا' },
  CZ: { fr: 'République tchèque',             en: 'Czech Republic',                 ar: 'التشيك' },
  EE: { fr: 'Estonie',                        en: 'Estonia',                        ar: 'إستونيا' },
  GE: { fr: 'Géorgie',                        en: 'Georgia',                        ar: 'جورجيا' },
  HU: { fr: 'Hongrie',                        en: 'Hungary',                        ar: 'هنغاريا' },
  IS: { fr: 'Islande',                        en: 'Iceland',                        ar: 'آيسلندا' },
  XK: { fr: 'Kosovo',                         en: 'Kosovo',                         ar: 'كوسوفو' },
  LV: { fr: 'Lettonie',                       en: 'Latvia',                         ar: 'لاتفيا' },
  LI: { fr: 'Liechtenstein',                  en: 'Liechtenstein',                  ar: 'ليختنشتاين' },
  LT: { fr: 'Lituanie',                       en: 'Lithuania',                      ar: 'ليتوانيا' },
  MT: { fr: 'Malte',                          en: 'Malta',                          ar: 'مالطا' },
  MC: { fr: 'Monaco',                         en: 'Monaco',                         ar: 'موناكو' },
  ME: { fr: 'Monténégro',                     en: 'Montenegro',                     ar: 'الجبل الأسود' },
  RU: { fr: 'Russie',                         en: 'Russia',                         ar: 'روسيا' },
  SM: { fr: 'Saint-Marin',                    en: 'San Marino',                     ar: 'سان مارينو' },
  RS: { fr: 'Serbie',                         en: 'Serbia',                         ar: 'صربيا' },
  SK: { fr: 'Slovaquie',                      en: 'Slovakia',                       ar: 'سلوفاكيا' },
  SI: { fr: 'Slovénie',                       en: 'Slovenia',                       ar: 'سلوفينيا' },
  VA: { fr: 'Vatican',                        en: 'Vatican City',                   ar: 'الفاتيكان' },
  // Asie (manquants)
  BN: { fr: 'Brunéi',                         en: 'Brunei',                         ar: 'بروناي' },
  BT: { fr: 'Bhoutan',                        en: 'Bhutan',                         ar: 'بوتان' },
  IL: { fr: 'Israël',                         en: 'Israel',                         ar: 'إسرائيل' },
  KP: { fr: 'Corée du Nord',                  en: 'North Korea',                    ar: 'كوريا الشمالية' },
  LA: { fr: 'Laos',                           en: 'Laos',                           ar: 'لاوس' },
  LK: { fr: 'Sri Lanka',                      en: 'Sri Lanka',                      ar: 'سريلانكا' },
  MN: { fr: 'Mongolie',                       en: 'Mongolia',                       ar: 'منغوليا' },
  MV: { fr: 'Maldives',                       en: 'Maldives',                       ar: 'المالديف' },
  NP: { fr: 'Népal',                          en: 'Nepal',                          ar: 'نيبال' },
  TL: { fr: 'Timor oriental',                 en: 'Timor-Leste',                    ar: 'تيمور الشرقية' },
  TW: { fr: 'Taïwan',                         en: 'Taiwan',                         ar: 'تايوان' },
  // Afrique (manquants)
  BW: { fr: 'Botswana',                       en: 'Botswana',                       ar: 'بوتسوانا' },
  CV: { fr: 'Cap-Vert',                       en: 'Cape Verde',                     ar: 'الرأس الأخضر' },
  ER: { fr: 'Érythrée',                       en: 'Eritrea',                        ar: 'إريتريا' },
  SZ: { fr: 'Eswatini',                       en: 'Eswatini',                       ar: 'إسواتيني' },
  LS: { fr: 'Lesotho',                        en: 'Lesotho',                        ar: 'ليسوتو' },
  LR: { fr: 'Libéria',                        en: 'Liberia',                        ar: 'ليبيريا' },
  MW: { fr: 'Malawi',                         en: 'Malawi',                         ar: 'مالاوي' },
  MU: { fr: 'Maurice',                        en: 'Mauritius',                      ar: 'موريشيوس' },
  SC: { fr: 'Seychelles',                     en: 'Seychelles',                     ar: 'سيشيل' },
  SS: { fr: 'Soudan du Sud',                  en: 'South Sudan',                    ar: 'جنوب السودان' },
  ST: { fr: 'Sao Tomé-et-Principe',           en: 'São Tomé and Príncipe',          ar: 'ساو تومي وبرينسيبي' },
  // Amériques
  AG: { fr: 'Antigua-et-Barbuda',             en: 'Antigua and Barbuda',            ar: 'أنتيغوا وبربودا' },
  BB: { fr: 'Barbade',                        en: 'Barbados',                       ar: 'بربادوس' },
  BZ: { fr: 'Belize',                         en: 'Belize',                         ar: 'بليز' },
  BO: { fr: 'Bolivie',                        en: 'Bolivia',                        ar: 'بوليفيا' },
  BR: { fr: 'Brésil',                         en: 'Brazil',                         ar: 'البرازيل' },
  BS: { fr: 'Bahamas',                        en: 'Bahamas',                        ar: 'جزر البهاما' },
  CL: { fr: 'Chili',                          en: 'Chile',                          ar: 'تشيلي' },
  CO: { fr: 'Colombie',                       en: 'Colombia',                       ar: 'كولومبيا' },
  CR: { fr: 'Costa Rica',                     en: 'Costa Rica',                     ar: 'كوستاريكا' },
  CU: { fr: 'Cuba',                           en: 'Cuba',                           ar: 'كوبا' },
  DM: { fr: 'Dominique',                      en: 'Dominica',                       ar: 'دومينيكا' },
  DO: { fr: 'République dominicaine',         en: 'Dominican Republic',             ar: 'جمهورية الدومينيكان' },
  EC: { fr: 'Équateur',                       en: 'Ecuador',                        ar: 'الإكوادور' },
  GD: { fr: 'Grenade',                        en: 'Grenada',                        ar: 'غرينادا' },
  GT: { fr: 'Guatemala',                      en: 'Guatemala',                      ar: 'غواتيمالا' },
  GY: { fr: 'Guyana',                         en: 'Guyana',                         ar: 'غيانا' },
  HT: { fr: 'Haïti',                          en: 'Haiti',                          ar: 'هايتي' },
  HN: { fr: 'Honduras',                       en: 'Honduras',                       ar: 'هندوراس' },
  JM: { fr: 'Jamaïque',                       en: 'Jamaica',                        ar: 'جامايكا' },
  KN: { fr: 'Saint-Kitts-et-Nevis',           en: 'Saint Kitts and Nevis',          ar: 'سانت كيتس ونيفيس' },
  LC: { fr: 'Sainte-Lucie',                   en: 'Saint Lucia',                    ar: 'سانت لوسيا' },
  NI: { fr: 'Nicaragua',                      en: 'Nicaragua',                      ar: 'نيكاراغوا' },
  PA: { fr: 'Panama',                         en: 'Panama',                         ar: 'بنما' },
  PE: { fr: 'Pérou',                          en: 'Peru',                           ar: 'بيرو' },
  PY: { fr: 'Paraguay',                       en: 'Paraguay',                       ar: 'باراغواي' },
  SR: { fr: 'Suriname',                       en: 'Suriname',                       ar: 'سورينام' },
  SV: { fr: 'Salvador',                       en: 'El Salvador',                    ar: 'السلفادور' },
  TT: { fr: 'Trinité-et-Tobago',              en: 'Trinidad and Tobago',            ar: 'ترينيداد وتوباغو' },
  UY: { fr: 'Uruguay',                        en: 'Uruguay',                        ar: 'أوروغواي' },
  VC: { fr: 'Saint-Vincent-et-les-Grenadines', en: 'Saint Vincent and the Grenadines', ar: 'سانت فينسنت وجزر غرينادين' },
  VE: { fr: 'Venezuela',                      en: 'Venezuela',                      ar: 'فنزويلا' },
  // Océanie
  FJ: { fr: 'Fidji',                          en: 'Fiji',                           ar: 'فيجي' },
  FM: { fr: 'Micronésie',                     en: 'Micronesia',                     ar: 'ميكرونيزيا' },
  KI: { fr: 'Kiribati',                       en: 'Kiribati',                       ar: 'كيريباتي' },
  MH: { fr: 'Îles Marshall',                  en: 'Marshall Islands',               ar: 'جزر مارشال' },
  NR: { fr: 'Nauru',                          en: 'Nauru',                          ar: 'ناورو' },
  NZ: { fr: 'Nouvelle-Zélande',               en: 'New Zealand',                    ar: 'نيوزيلندا' },
  PG: { fr: 'Papouasie-Nouvelle-Guinée',      en: 'Papua New Guinea',               ar: 'بابوا غينيا الجديدة' },
  PW: { fr: 'Palaos',                         en: 'Palau',                          ar: 'بالاو' },
  SB: { fr: 'Îles Salomon',                   en: 'Solomon Islands',                ar: 'جزر سليمان' },
  TO: { fr: 'Tonga',                          en: 'Tonga',                          ar: 'تونغا' },
  TV: { fr: 'Tuvalu',                         en: 'Tuvalu',                         ar: 'توفالو' },
  VU: { fr: 'Vanuatu',                        en: 'Vanuatu',                        ar: 'فانواتو' },
  WS: { fr: 'Samoa',                          en: 'Samoa',                          ar: 'ساموا' },
};

/**
 * Returns the country name in the given locale ('fr-FR', 'en-US', 'ar-SA', …)
 * from the ISO 3166-1 alpha-2 code. Falls back to the code itself if unknown.
 */
export function getCountryName(isoCode, locale) {
  if (!isoCode) return null;
  const entry = NAMES[isoCode.toUpperCase()];
  if (!entry) return isoCode;
  const lang = (locale ?? 'fr').split('-')[0].split('_')[0];
  return entry[lang] ?? entry.fr ?? isoCode;
}
