// ISO 3166-1 alpha-2 → { fr, en, ar, de, es, it, pt, ru, tr, id, ms, bn, ur, ja, ko, bm }
const NAMES = {
  AF: { fr: 'Afghanistan',           en: 'Afghanistan',              ar: 'أفغانستان',                    de: 'Afghanistan',          es: 'Afganistán',           it: 'Afghanistan',          pt: 'Afeganistão',          ru: 'Афганистан',           tr: 'Afganistan',       id: 'Afganistan',       ms: 'Afghanistan',      bn: 'আফগানিস্তান',      ur: 'افغانستان',     ja: 'アフガニスタン',       ko: '아프가니스탄',    bm: 'Afganistani' },
  DZ: { fr: 'Algérie',               en: 'Algeria',                  ar: 'الجزائر',                      de: 'Algerien',             es: 'Argelia',              it: 'Algeria',              pt: 'Argélia',              ru: 'Алжир',                tr: 'Cezayir',          id: 'Aljazair',         ms: 'Algeria',          bn: 'আলজেরিয়া',        ur: 'الجزائر',       ja: 'アルジェリア',         ko: '알제리',         bm: 'Alajeri' },
  DE: { fr: 'Allemagne',             en: 'Germany',                  ar: 'ألمانيا',                      de: 'Deutschland',          es: 'Alemania',             it: 'Germania',             pt: 'Alemanha',             ru: 'Германия',             tr: 'Almanya',          id: 'Jerman',           ms: 'Jerman',           bn: 'জার্মানি',          ur: 'جرمنی',         ja: 'ドイツ',               ko: '독일',           bm: 'Alimani' },
  AO: { fr: 'Angola',                en: 'Angola',                   ar: 'أنغولا',                       de: 'Angola',               es: 'Angola',               it: 'Angola',               pt: 'Angola',               ru: 'Ангола',               tr: 'Angola',           id: 'Angola',           ms: 'Angola',           bn: 'অ্যাঙ্গোলা',        ur: 'انگولا',        ja: 'アンゴラ',             ko: '앙골라',         bm: 'Angɔla' },
  SA: { fr: 'Arabie Saoudite',       en: 'Saudi Arabia',             ar: 'المملكة العربية السعودية',     de: 'Saudi-Arabien',        es: 'Arabia Saudita',       it: 'Arabia Saudita',       pt: 'Arábia Saudita',       ru: 'Саудовская Аравия',    tr: 'Suudi Arabistan',  id: 'Arab Saudi',       ms: 'Arab Saudi',       bn: 'সৌদি আরব',          ur: 'سعودی عرب',     ja: 'サウジアラビア',       ko: '사우디아라비아',  bm: 'Arabi Sawuditi' },
  AR: { fr: 'Argentine',             en: 'Argentina',                ar: 'الأرجنتين',                    de: 'Argentinien',          es: 'Argentina',            it: 'Argentina',            pt: 'Argentina',            ru: 'Аргентина',            tr: 'Arjantin',         id: 'Argentina',        ms: 'Argentina',        bn: 'আর্জেন্টিনা',       ur: 'ارجنٹینا',      ja: 'アルゼンチン',         ko: '아르헨티나',     bm: 'Arijantini' },
  AU: { fr: 'Australie',             en: 'Australia',                ar: 'أستراليا',                     de: 'Australien',           es: 'Australia',            it: 'Australia',            pt: 'Austrália',            ru: 'Австралия',            tr: 'Avustralya',       id: 'Australia',        ms: 'Australia',        bn: 'অস্ট্রেলিয়া',      ur: 'آسٹریلیا',      ja: 'オーストラリア',       ko: '호주',           bm: 'Ositirali' },
  AT: { fr: 'Autriche',              en: 'Austria',                  ar: 'النمسا',                       de: 'Österreich',           es: 'Austria',              it: 'Austria',              pt: 'Áustria',              ru: 'Австрия',              tr: 'Avusturya',        id: 'Austria',          ms: 'Austria',          bn: 'অস্ট্রিয়া',         ur: 'آسٹریا',        ja: 'オーストリア',         ko: '오스트리아',     bm: 'Otirisi' },
  AZ: { fr: 'Azerbaïdjan',           en: 'Azerbaijan',               ar: 'أذربيجان',                     de: 'Aserbaidschan',        es: 'Azerbaiyán',           it: 'Azerbaigian',          pt: 'Azerbaijão',           ru: 'Азербайджан',          tr: 'Azerbaycan',       id: 'Azerbaijan',       ms: 'Azerbaijan',       bn: 'আজারবাইজান',        ur: 'آذربائیجان',    ja: 'アゼルバイジャン',     ko: '아제르바이잔',   bm: 'Azɛrbayjani' },
  BH: { fr: 'Bahreïn',               en: 'Bahrain',                  ar: 'البحرين',                      de: 'Bahrain',              es: 'Baréin',               it: 'Bahrein',              pt: 'Barein',               ru: 'Бахрейн',              tr: 'Bahreyn',          id: 'Bahrain',          ms: 'Bahrain',          bn: 'বাহরাইন',           ur: 'بحرین',         ja: 'バーレーン',           ko: '바레인',         bm: 'Bahrɛni' },
  BD: { fr: 'Bangladesh',            en: 'Bangladesh',               ar: 'بنغلاديش',                     de: 'Bangladesch',          es: 'Bangladés',            it: 'Bangladesh',           pt: 'Bangladesh',           ru: 'Бангладеш',            tr: 'Bangladeş',        id: 'Bangladesh',       ms: 'Bangladesh',       bn: 'বাংলাদেশ',          ur: 'بنگلہ دیش',     ja: 'バングラデシュ',       ko: '방글라데시',     bm: 'Bangaladɛsi' },
  BE: { fr: 'Belgique',              en: 'Belgium',                  ar: 'بلجيكا',                       de: 'Belgien',              es: 'Bélgica',              it: 'Belgio',               pt: 'Bélgica',              ru: 'Бельгия',              tr: 'Belçika',          id: 'Belgia',           ms: 'Belgium',          bn: 'বেলজিয়াম',          ur: 'بیلجیم',        ja: 'ベルギー',             ko: '벨기에',         bm: 'Bɛliziki' },
  BJ: { fr: 'Bénin',                 en: 'Benin',                    ar: 'بنين',                         de: 'Benin',                es: 'Benín',                it: 'Benin',                pt: 'Benin',                ru: 'Бенин',                tr: 'Benin',            id: 'Benin',            ms: 'Benin',            bn: 'বেনিন',             ur: 'بینن',          ja: 'ベナン',               ko: '베냉',           bm: 'Benɛn' },
  MM: { fr: 'Birmanie',              en: 'Myanmar',                  ar: 'ميانمار',                      de: 'Myanmar',              es: 'Myanmar',              it: 'Myanmar',              pt: 'Myanmar',              ru: 'Мьянма',               tr: 'Myanmar',          id: 'Myanmar',          ms: 'Myanmar',          bn: 'মিয়ানমার',          ur: 'میانمار',       ja: 'ミャンマー',           ko: '미얀마',         bm: 'Miyanimari' },
  BA: { fr: 'Bosnie-Herzégovine',    en: 'Bosnia and Herzegovina',   ar: 'البوسنة والهرسك',              de: 'Bosnien und Herzegowina', es: 'Bosnia y Herzegovina', it: 'Bosnia ed Erzegovina', pt: 'Bósnia e Herzegovina', ru: 'Босния и Герцеговина', tr: 'Bosna-Hersek',     id: 'Bosnia dan Herzegovina', ms: 'Bosnia dan Herzegovina', bn: 'বসনিয়া ও হার্জেগোভিনা', ur: 'بوسنیا و ہرزیگووینا', ja: 'ボスニア・ヘルツェゴビナ', ko: '보스니아 헤르체고비나', bm: 'Bozini' },
  BG: { fr: 'Bulgarie',              en: 'Bulgaria',                 ar: 'بلغاريا',                      de: 'Bulgarien',            es: 'Bulgaria',             it: 'Bulgaria',             pt: 'Bulgária',             ru: 'Болгария',             tr: 'Bulgaristan',      id: 'Bulgaria',         ms: 'Bulgaria',         bn: 'বুলগেরিয়া',         ur: 'بلغاریہ',       ja: 'ブルガリア',           ko: '불가리아',       bm: 'Buligari' },
  BF: { fr: 'Burkina Faso',          en: 'Burkina Faso',             ar: 'بوركينا فاسو',                 de: 'Burkina Faso',         es: 'Burkina Faso',         it: 'Burkina Faso',         pt: 'Burkina Faso',         ru: 'Буркина-Фасо',         tr: 'Burkina Faso',     id: 'Burkina Faso',     ms: 'Burkina Faso',     bn: 'বুর্কিনা ফাসো',      ur: 'برکینا فاسو',   ja: 'ブルキナファソ',       ko: '부르키나파소',   bm: 'Burukina Faso' },
  BI: { fr: 'Burundi',               en: 'Burundi',                  ar: 'بوروندي',                      de: 'Burundi',              es: 'Burundi',              it: 'Burundi',              pt: 'Burundi',              ru: 'Бурунди',              tr: 'Burundi',          id: 'Burundi',          ms: 'Burundi',          bn: 'বুরুন্ডি',           ur: 'برونڈی',        ja: 'ブルンジ',             ko: '부룬디',         bm: 'Burundi' },
  KH: { fr: 'Cambodge',              en: 'Cambodia',                 ar: 'كمبوديا',                      de: 'Kambodscha',           es: 'Camboya',              it: 'Cambogia',             pt: 'Camboja',              ru: 'Камбоджа',             tr: 'Kamboçya',         id: 'Kamboja',          ms: 'Kemboja',          bn: 'কম্বোডিয়া',         ur: 'کمبوڈیا',       ja: 'カンボジア',           ko: '캄보디아',       bm: 'Kanbɔji' },
  CM: { fr: 'Cameroun',              en: 'Cameroon',                 ar: 'الكاميرون',                    de: 'Kamerun',              es: 'Camerún',              it: 'Camerun',              pt: 'Camarões',             ru: 'Камерун',              tr: 'Kamerun',          id: 'Kamerun',          ms: 'Kamerun',          bn: 'ক্যামেরুন',          ur: 'کیمرون',        ja: 'カメルーン',           ko: '카메룬',         bm: 'Kameruni' },
  CA: { fr: 'Canada',                en: 'Canada',                   ar: 'كندا',                         de: 'Kanada',               es: 'Canadá',               it: 'Canada',               pt: 'Canadá',               ru: 'Канада',               tr: 'Kanada',           id: 'Kanada',           ms: 'Kanada',           bn: 'কানাডা',            ur: 'کینیڈا',        ja: 'カナダ',               ko: '캐나다',         bm: 'Kanada' },
  CF: { fr: 'Centrafrique',          en: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى',      de: 'Zentralafrikanische Republik', es: 'República Centroafricana', it: 'Repubblica Centrafricana', pt: 'República Centro-Africana', ru: 'Центральноафриканская Республика', tr: 'Orta Afrika Cumhuriyeti', id: 'Republik Afrika Tengah', ms: 'Republik Afrika Tengah', bn: 'মধ্য আফ্রিকান প্রজাতন্ত্র', ur: 'وسطی افریقی جمہوریہ', ja: '中央アフリカ共和国', ko: '중앙아프리카 공화국', bm: 'Afirik Tilen' },
  KM: { fr: 'Comores',               en: 'Comoros',                  ar: 'جزر القمر',                    de: 'Komoren',              es: 'Comoras',              it: 'Comore',               pt: 'Comores',              ru: 'Коморы',               tr: 'Komorlar',         id: 'Komoro',           ms: 'Komoro',           bn: 'কোমোরোস',           ur: 'کوموروس',       ja: 'コモロ',               ko: '코모로',         bm: 'Kɔmɔri' },
  CG: { fr: 'Congo',                 en: 'Republic of the Congo',    ar: 'الكونغو',                      de: 'Republik Kongo',       es: 'República del Congo',  it: 'Repubblica del Congo', pt: 'República do Congo',   ru: 'Республика Конго',     tr: 'Kongo Cumhuriyeti', id: 'Republik Kongo',  ms: 'Republik Kongo',   bn: 'কঙ্গো প্রজাতন্ত্র',  ur: 'جمہوریہ کانگو', ja: 'コンゴ共和国',         ko: '콩고 공화국',    bm: 'Kɔngɔ' },
  CD: { fr: 'RD Congo',              en: 'DR Congo',                 ar: 'الكونغو الديمقراطية',          de: 'DR Kongo',             es: 'República Democrática del Congo', it: 'Repubblica Democratica del Congo', pt: 'República Democrática do Congo', ru: 'ДР Конго',       tr: 'Demokratik Kongo Cumhuriyeti', id: 'Kongo', ms: 'Congo', bn: 'কঙ্গো গণতান্ত্রিক প্রজাতন্ত্র', ur: 'جمہوری جمہوریہ کانگو', ja: 'コンゴ民主共和国', ko: '콩고 민주공화국', bm: 'Kɔngɔ Demokarasi' },
  CI: { fr: "Côte d'Ivoire",         en: "Côte d'Ivoire",            ar: 'ساحل العاج',                   de: 'Elfenbeinküste',       es: 'Costa de Marfil',      it: "Costa d'Avorio",       pt: 'Costa do Marfim',      ru: "Кот-д'Ивуар",          tr: 'Fildişi Sahili',   id: 'Pantai Gading',    ms: 'Pantai Gading',    bn: 'আইভরি কোস্ট',        ur: 'آئیوری کوسٹ',   ja: 'コートジボワール',     ko: '코트디부아르',   bm: 'Kodivuwari' },
  DK: { fr: 'Danemark',              en: 'Denmark',                  ar: 'الدنمارك',                     de: 'Dänemark',             es: 'Dinamarca',            it: 'Danimarca',            pt: 'Dinamarca',            ru: 'Дания',                tr: 'Danimarka',        id: 'Denmark',          ms: 'Denmark',          bn: 'ডেনমার্ক',           ur: 'ڈنمارک',        ja: 'デンマーク',           ko: '덴마크',         bm: 'Danemarki' },
  DJ: { fr: 'Djibouti',              en: 'Djibouti',                 ar: 'جيبوتي',                       de: 'Dschibuti',            es: 'Yibuti',               it: 'Gibuti',               pt: 'Djibuti',              ru: 'Джибути',              tr: 'Cibuti',           id: 'Djibouti',         ms: 'Djibouti',         bn: 'জিবুতি',            ur: 'جبوتی',         ja: 'ジブチ',               ko: '지부티',         bm: 'Jibuti' },
  EG: { fr: 'Égypte',                en: 'Egypt',                    ar: 'مصر',                          de: 'Ägypten',              es: 'Egipto',               it: 'Egitto',               pt: 'Egito',                ru: 'Египет',               tr: 'Mısır',            id: 'Mesir',            ms: 'Mesir',            bn: 'মিশর',              ur: 'مصر',           ja: 'エジプト',             ko: '이집트',         bm: 'Ezipti' },
  AE: { fr: 'Émirats arabes unis',   en: 'United Arab Emirates',     ar: 'الإمارات العربية المتحدة',     de: 'Vereinigte Arabische Emirate', es: 'Emiratos Árabes Unidos', it: 'Emirati Arabi Uniti', pt: 'Emirados Árabes Unidos', ru: 'ОАЭ',              tr: 'Birleşik Arap Emirlikleri', id: 'Uni Emirat Arab', ms: 'Emiriah Arab Bersatu', bn: 'সংযুক্ত আরব আমিরাত', ur: 'متحدہ عرب امارات', ja: 'アラブ首長国連邦', ko: '아랍에미리트',    bm: 'Arabi Imira' },
  ES: { fr: 'Espagne',               en: 'Spain',                    ar: 'إسبانيا',                      de: 'Spanien',              es: 'España',               it: 'Spagna',               pt: 'Espanha',              ru: 'Испания',              tr: 'İspanya',          id: 'Spanyol',          ms: 'Sepanyol',         bn: 'স্পেন',             ur: 'سپین',          ja: 'スペイン',             ko: '스페인',         bm: 'Esipaɲi' },
  ET: { fr: 'Éthiopie',              en: 'Ethiopia',                 ar: 'إثيوبيا',                      de: 'Äthiopien',            es: 'Etiopía',              it: 'Etiopia',              pt: 'Etiópia',              ru: 'Эфиопия',              tr: 'Etiyopya',         id: 'Etiopia',          ms: 'Ethiopia',         bn: 'ইথিওপিয়া',         ur: 'ایتھوپیا',      ja: 'エチオピア',           ko: '에티오피아',     bm: 'Etsiyɔpi' },
  FI: { fr: 'Finlande',              en: 'Finland',                  ar: 'فنلندا',                       de: 'Finnland',             es: 'Finlandia',            it: 'Finlandia',            pt: 'Finlândia',            ru: 'Финляндия',            tr: 'Finlandiya',       id: 'Finlandia',        ms: 'Finland',          bn: 'ফিনল্যান্ড',         ur: 'فن لینڈ',       ja: 'フィンランド',         ko: '핀란드',         bm: 'Finilandi' },
  FR: { fr: 'France',                en: 'France',                   ar: 'فرنسا',                        de: 'Frankreich',           es: 'Francia',              it: 'Francia',              pt: 'França',               ru: 'Франция',              tr: 'Fransa',           id: 'Prancis',          ms: 'Perancis',         bn: 'ফ্রান্স',            ur: 'فرانس',         ja: 'フランス',             ko: '프랑스',         bm: 'Faransi' },
  GA: { fr: 'Gabon',                 en: 'Gabon',                    ar: 'الغابون',                      de: 'Gabun',                es: 'Gabón',                it: 'Gabon',                pt: 'Gabão',                ru: 'Габон',                tr: 'Gabon',            id: 'Gabon',            ms: 'Gabon',            bn: 'গ্যাবন',            ur: 'گیبون',         ja: 'ガボン',               ko: '가봉',           bm: 'Gabɔn' },
  GM: { fr: 'Gambie',                en: 'Gambia',                   ar: 'غامبيا',                       de: 'Gambia',               es: 'Gambia',               it: 'Gambia',               pt: 'Gâmbia',               ru: 'Гамбия',               tr: 'Gambiya',          id: 'Gambia',           ms: 'Gambia',           bn: 'গাম্বিয়া',          ur: 'گیمبیا',        ja: 'ガンビア',             ko: '감비아',         bm: 'Ganbi' },
  GH: { fr: 'Ghana',                 en: 'Ghana',                    ar: 'غانا',                         de: 'Ghana',                es: 'Ghana',                it: 'Ghana',                pt: 'Gana',                 ru: 'Гана',                 tr: 'Gana',             id: 'Ghana',            ms: 'Ghana',            bn: 'ঘানা',              ur: 'گھانا',         ja: 'ガーナ',               ko: '가나',           bm: 'Gana' },
  GR: { fr: 'Grèce',                 en: 'Greece',                   ar: 'اليونان',                      de: 'Griechenland',         es: 'Grecia',               it: 'Grecia',               pt: 'Grécia',               ru: 'Греция',               tr: 'Yunanistan',       id: 'Yunani',           ms: 'Greece',           bn: 'গ্রীস',             ur: 'یونان',         ja: 'ギリシャ',             ko: '그리스',         bm: 'Grɛsi' },
  GN: { fr: 'Guinée',                en: 'Guinea',                   ar: 'غينيا',                        de: 'Guinea',               es: 'Guinea',               it: 'Guinea',               pt: 'Guiné',                ru: 'Гвинея',               tr: 'Gine',             id: 'Guinea',           ms: 'Guinea',           bn: 'গিনি',              ur: 'گنی',           ja: 'ギニア',               ko: '기니',           bm: 'Gine' },
  GW: { fr: 'Guinée-Bissau',         en: 'Guinea-Bissau',            ar: 'غينيا بيساو',                  de: 'Guinea-Bissau',        es: 'Guinea-Bisáu',         it: 'Guinea-Bissau',        pt: 'Guiné-Bissau',         ru: 'Гвинея-Бисау',         tr: 'Gine-Bissau',      id: 'Guinea-Bissau',    ms: 'Guinea-Bissau',    bn: 'গিনি-বিসাউ',         ur: 'گنی بساؤ',      ja: 'ギニアビサウ',         ko: '기니비사우',     bm: 'Gine Bisawo' },
  GQ: { fr: 'Guinée équatoriale',    en: 'Equatorial Guinea',        ar: 'غينيا الاستوائية',             de: 'Äquatorialguinea',     es: 'Guinea Ecuatorial',    it: 'Guinea Equatoriale',   pt: 'Guiné Equatorial',     ru: 'Экваториальная Гвинея', tr: 'Ekvator Ginesi',  id: 'Guinea Ekuatorial', ms: 'Guinea Khatulistiwa', bn: 'বিষুবীয় গিনি', ur: 'استوائی گنی',   ja: '赤道ギニア',           ko: '적도 기니',      bm: 'Gine Ekwatori' },
  IN: { fr: 'Inde',                  en: 'India',                    ar: 'الهند',                        de: 'Indien',               es: 'India',                it: 'India',                pt: 'Índia',                ru: 'Индия',                tr: 'Hindistan',        id: 'India',            ms: 'India',            bn: 'ভারত',              ur: 'ہندوستان',      ja: 'インド',               ko: '인도',           bm: 'Ɛndu' },
  ID: { fr: 'Indonésie',             en: 'Indonesia',                ar: 'إندونيسيا',                    de: 'Indonesien',           es: 'Indonesia',            it: 'Indonesia',            pt: 'Indonésia',            ru: 'Индонезия',            tr: 'Endonezya',        id: 'Indonesia',        ms: 'Indonesia',        bn: 'ইন্দোনেশিয়া',       ur: 'انڈونیشیا',     ja: 'インドネシア',         ko: '인도네시아',     bm: 'Indonezi' },
  IQ: { fr: 'Irak',                  en: 'Iraq',                     ar: 'العراق',                       de: 'Irak',                 es: 'Irak',                 it: 'Iraq',                 pt: 'Iraque',               ru: 'Ирак',                 tr: 'Irak',             id: 'Irak',             ms: 'Iraq',             bn: 'ইরাক',              ur: 'عراق',          ja: 'イラク',               ko: '이라크',         bm: 'Iraki' },
  IR: { fr: 'Iran',                  en: 'Iran',                     ar: 'إيران',                        de: 'Iran',                 es: 'Irán',                 it: 'Iran',                 pt: 'Irã',                  ru: 'Иран',                 tr: 'İran',             id: 'Iran',             ms: 'Iran',             bn: 'ইরান',              ur: 'ایران',         ja: 'イラン',               ko: '이란',           bm: 'Irani' },
  IE: { fr: 'Irlande',               en: 'Ireland',                  ar: 'أيرلندا',                      de: 'Irland',               es: 'Irlanda',              it: 'Irlanda',              pt: 'Irlanda',              ru: 'Ирландия',             tr: 'İrlanda',          id: 'Irlandia',         ms: 'Ireland',          bn: 'আয়ারল্যান্ড',       ur: 'آئرلینڈ',       ja: 'アイルランド',         ko: '아일랜드',       bm: 'Irilandi' },
  IT: { fr: 'Italie',                en: 'Italy',                    ar: 'إيطاليا',                      de: 'Italien',              es: 'Italia',               it: 'Italia',               pt: 'Itália',               ru: 'Италия',               tr: 'İtalya',           id: 'Italia',           ms: 'Itali',            bn: 'ইতালি',             ur: 'اٹلی',          ja: 'イタリア',             ko: '이탈리아',       bm: 'Itali' },
  JO: { fr: 'Jordanie',              en: 'Jordan',                   ar: 'الأردن',                       de: 'Jordanien',            es: 'Jordania',             it: 'Giordania',            pt: 'Jordânia',             ru: 'Иордания',             tr: 'Ürdün',            id: 'Yordania',         ms: 'Jordan',           bn: 'জর্দান',            ur: 'اردن',          ja: 'ヨルダン',             ko: '요르단',         bm: 'Jordani' },
  KZ: { fr: 'Kazakhstan',            en: 'Kazakhstan',               ar: 'كازاخستان',                    de: 'Kasachstan',           es: 'Kazajistán',           it: 'Kazakistan',           pt: 'Cazaquistão',          ru: 'Казахстан',            tr: 'Kazakistan',       id: 'Kazakhstan',       ms: 'Kazakhstan',       bn: 'কাজাখস্তান',         ur: 'قازقستان',      ja: 'カザフスタン',         ko: '카자흐스탄',     bm: 'Kazakistani' },
  KE: { fr: 'Kenya',                 en: 'Kenya',                    ar: 'كينيا',                        de: 'Kenia',                es: 'Kenia',                it: 'Kenya',                pt: 'Quénia',               ru: 'Кения',                tr: 'Kenya',            id: 'Kenya',            ms: 'Kenya',            bn: 'কেনিয়া',           ur: 'کینیا',         ja: 'ケニア',               ko: '케냐',           bm: 'Kɛnya' },
  KG: { fr: 'Kirghizistan',          en: 'Kyrgyzstan',               ar: 'قيرغيزستان',                   de: 'Kirgisistan',          es: 'Kirguistán',           it: 'Kirghizistan',         pt: 'Quirguistão',          ru: 'Киргизия',             tr: 'Kırgızistan',      id: 'Kirgistan',        ms: 'Kyrgyzstan',       bn: 'কির্গিজস্তান',       ur: 'کرغیزستان',     ja: 'キルギス',             ko: '키르기스스탄',   bm: 'Kirigizistani' },
  KW: { fr: 'Koweït',                en: 'Kuwait',                   ar: 'الكويت',                       de: 'Kuwait',               es: 'Kuwait',               it: 'Kuwait',               pt: 'Kuwait',               ru: 'Кувейт',               tr: 'Kuveyt',           id: 'Kuwait',           ms: 'Kuwait',           bn: 'কুয়েত',             ur: 'کویت',          ja: 'クウェート',           ko: '쿠웨이트',       bm: 'Koweti' },
  LB: { fr: 'Liban',                 en: 'Lebanon',                  ar: 'لبنان',                        de: 'Libanon',              es: 'Líbano',               it: 'Libano',               pt: 'Líbano',               ru: 'Ливан',                tr: 'Lübnan',           id: 'Lebanon',          ms: 'Lubnan',           bn: 'লেবানন',            ur: 'لبنان',         ja: 'レバノン',             ko: '레바논',         bm: 'Libani' },
  LY: { fr: 'Libye',                 en: 'Libya',                    ar: 'ليبيا',                        de: 'Libyen',               es: 'Libia',                it: 'Libia',                pt: 'Líbia',                ru: 'Ливия',                tr: 'Libya',            id: 'Libya',            ms: 'Libya',            bn: 'লিবিয়া',           ur: 'لیبیا',         ja: 'リビア',               ko: '리비아',         bm: 'Libi' },
  LU: { fr: 'Luxembourg',            en: 'Luxembourg',               ar: 'لوكسمبورغ',                    de: 'Luxemburg',            es: 'Luxemburgo',           it: 'Lussemburgo',          pt: 'Luxemburgo',           ru: 'Люксембург',            tr: 'Lüksemburg',       id: 'Luksemburg',       ms: 'Luxembourg',       bn: 'লুক্সেমবার্গ',       ur: 'لکسمبرگ',       ja: 'ルクセンブルク',       ko: '룩셈부르크',     bm: 'Luksɛmburi' },
  MK: { fr: 'Macédoine du Nord',     en: 'North Macedonia',          ar: 'مقدونيا الشمالية',             de: 'Nordmazedonien',       es: 'Macedonia del Norte',  it: 'Macedonia del Nord',   pt: 'Macedónia do Norte',   ru: 'Северная Македония',   tr: 'Kuzey Makedonya',  id: 'Makedonia Utara',  ms: 'Macedonia Utara',  bn: 'উত্তর মেসিডোনিয়া',  ur: 'شمالی مقدونیہ',  ja: '北マケドニア',         ko: '북마케도니아',   bm: 'Masiduwan Kɔrɔ' },
  MG: { fr: 'Madagascar',            en: 'Madagascar',               ar: 'مدغشقر',                       de: 'Madagaskar',           es: 'Madagascar',           it: 'Madagascar',           pt: 'Madagáscar',           ru: 'Мадагаскар',           tr: 'Madagaskar',       id: 'Madagaskar',       ms: 'Madagaskar',       bn: 'মাদাগাস্কার',        ur: 'مڈغاسکر',       ja: 'マダガスカル',         ko: '마다가스카르',    bm: 'Madagasikari' },
  MY: { fr: 'Malaisie',              en: 'Malaysia',                 ar: 'ماليزيا',                      de: 'Malaysia',             es: 'Malasia',              it: 'Malaysia',             pt: 'Malásia',              ru: 'Малайзия',             tr: 'Malezya',          id: 'Malaysia',         ms: 'Malaysia',         bn: 'মালয়েশিয়া',        ur: 'ملائیشیا',      ja: 'マレーシア',           ko: '말레이시아',     bm: 'Malɛzi' },
  ML: { fr: 'Mali',                  en: 'Mali',                     ar: 'مالي',                         de: 'Mali',                 es: 'Malí',                 it: 'Mali',                 pt: 'Mali',                 ru: 'Мали',                 tr: 'Mali',             id: 'Mali',             ms: 'Mali',             bn: 'মালি',              ur: 'مالی',          ja: 'マリ',                 ko: '말리',           bm: 'Mali' },
  MA: { fr: 'Maroc',                 en: 'Morocco',                  ar: 'المغرب',                       de: 'Marokko',              es: 'Marruecos',            it: 'Marocco',              pt: 'Marrocos',             ru: 'Марокко',              tr: 'Fas',              id: 'Maroko',           ms: 'Maghribi',         bn: 'মরক্কো',            ur: 'مراکش',         ja: 'モロッコ',             ko: '모로코',         bm: 'Marɔku' },
  MR: { fr: 'Mauritanie',            en: 'Mauritania',               ar: 'موريتانيا',                    de: 'Mauretanien',          es: 'Mauritania',           it: 'Mauritania',           pt: 'Mauritânia',           ru: 'Мавритания',           tr: 'Moritanya',        id: 'Mauritania',       ms: 'Mauritania',       bn: 'মৌরিতানিয়া',        ur: 'موریتانیہ',     ja: 'モーリタニア',         ko: '모리타니',       bm: 'Muritani' },
  MX: { fr: 'Mexique',               en: 'Mexico',                   ar: 'المكسيك',                      de: 'Mexiko',               es: 'México',               it: 'Messico',              pt: 'México',               ru: 'Мексика',              tr: 'Meksika',          id: 'Meksiko',          ms: 'Mexico',           bn: 'মেক্সিকো',           ur: 'میکسیکو',       ja: 'メキシコ',             ko: '멕시코',         bm: 'Mɛksiki' },
  MD: { fr: 'Moldavie',              en: 'Moldova',                  ar: 'مولدوفا',                      de: 'Moldau',               es: 'Moldavia',             it: 'Moldavia',             pt: 'Moldávia',             ru: 'Молдова',              tr: 'Moldova',          id: 'Moldova',          ms: 'Moldova',          bn: 'মলদোভা',            ur: 'مالدووا',       ja: 'モルドバ',             ko: '몰도바',         bm: 'Mɔldawi' },
  MZ: { fr: 'Mozambique',            en: 'Mozambique',               ar: 'موزمبيق',                      de: 'Mosambik',             es: 'Mozambique',           it: 'Mozambico',            pt: 'Moçambique',           ru: 'Мозамбик',             tr: 'Mozambik',         id: 'Mozambik',         ms: 'Mozambik',         bn: 'মোজাম্বিক',          ur: 'موزمبیق',       ja: 'モザンビーク',         ko: '모잠비크',       bm: 'Mozambiki' },
  NA: { fr: 'Namibie',               en: 'Namibia',                  ar: 'ناميبيا',                      de: 'Namibia',              es: 'Namibia',              it: 'Namibia',              pt: 'Namíbia',              ru: 'Намибия',              tr: 'Namibya',          id: 'Namibia',          ms: 'Namibia',          bn: 'নামিবিয়া',           ur: 'نامیبیا',       ja: 'ナミビア',             ko: '나미비아',       bm: 'Namibi' },
  NE: { fr: 'Niger',                 en: 'Niger',                    ar: 'النيجر',                       de: 'Niger',                es: 'Níger',                it: 'Niger',                pt: 'Níger',                ru: 'Нигер',                tr: 'Nijer',            id: 'Niger',            ms: 'Niger',            bn: 'নাইজার',            ur: 'نائجر',         ja: 'ニジェール',           ko: '니제르',         bm: 'Niyɛri' },
  NG: { fr: 'Nigéria',               en: 'Nigeria',                  ar: 'نيجيريا',                      de: 'Nigeria',              es: 'Nigeria',              it: 'Nigeria',              pt: 'Nigéria',              ru: 'Нигерия',              tr: 'Nijerya',          id: 'Nigeria',          ms: 'Nigeria',          bn: 'নাইজেরিয়া',         ur: 'نائیجیریا',     ja: 'ナイジェリア',         ko: '나이지리아',     bm: 'Nijeriya' },
  NO: { fr: 'Norvège',               en: 'Norway',                   ar: 'النرويج',                      de: 'Norwegen',             es: 'Noruega',              it: 'Norvegia',             pt: 'Noruega',              ru: 'Норвегия',             tr: 'Norveç',           id: 'Norwegia',         ms: 'Norway',           bn: 'নরওয়ে',             ur: 'ناروے',         ja: 'ノルウェー',           ko: '노르웨이',       bm: 'Nɔriyɛji' },
  NL: { fr: 'Pays-Bas',              en: 'Netherlands',              ar: 'هولندا',                       de: 'Niederlande',          es: 'Países Bajos',         it: 'Paesi Bassi',          pt: 'Países Baixos',        ru: 'Нидерланды',           tr: 'Hollanda',         id: 'Belanda',          ms: 'Belanda',          bn: 'নেদারল্যান্ডস',      ur: 'نیدرلینڈز',     ja: 'オランダ',             ko: '네덜란드',       bm: 'Peyibasi' },
  PK: { fr: 'Pakistan',              en: 'Pakistan',                 ar: 'باكستان',                      de: 'Pakistan',             es: 'Pakistán',             it: 'Pakistan',             pt: 'Paquistão',            ru: 'Пакистан',             tr: 'Pakistan',         id: 'Pakistan',         ms: 'Pakistan',         bn: 'পাকিস্তান',          ur: 'پاکستان',       ja: 'パキスタン',           ko: '파키스탄',       bm: 'Pakistani' },
  PS: { fr: 'Palestine',             en: 'Palestine',                ar: 'فلسطين',                       de: 'Palästina',            es: 'Palestina',            it: 'Palestina',            pt: 'Palestina',            ru: 'Палестина',            tr: 'Filistin',         id: 'Palestina',        ms: 'Palestin',         bn: 'ফিলিস্তিন',          ur: 'فلسطین',        ja: 'パレスチナ',           ko: '팔레스타인',     bm: 'Palɛsitini' },
  PH: { fr: 'Philippines',           en: 'Philippines',              ar: 'الفلبين',                      de: 'Philippinen',          es: 'Filipinas',            it: 'Filippine',            pt: 'Filipinas',            ru: 'Филиппины',            tr: 'Filipinler',       id: 'Filipina',         ms: 'Filipina',         bn: 'ফিলিপাইন',           ur: 'فلپائن',        ja: 'フィリピン',           ko: '필리핀',         bm: 'Filipini' },
  PL: { fr: 'Pologne',               en: 'Poland',                   ar: 'بولندا',                       de: 'Polen',                es: 'Polonia',              it: 'Polonia',              pt: 'Polónia',              ru: 'Польша',               tr: 'Polonya',          id: 'Polandia',         ms: 'Poland',           bn: 'পোল্যান্ড',          ur: 'پولینڈ',        ja: 'ポーランド',           ko: '폴란드',         bm: 'Polɔni' },
  PT: { fr: 'Portugal',              en: 'Portugal',                 ar: 'البرتغال',                     de: 'Portugal',             es: 'Portugal',             it: 'Portogallo',           pt: 'Portugal',             ru: 'Португалия',           tr: 'Portekiz',         id: 'Portugal',         ms: 'Portugal',         bn: 'পর্তুগাল',           ur: 'پرتگال',        ja: 'ポルトガル',           ko: '포르투갈',       bm: 'Pɔrigali' },
  QA: { fr: 'Qatar',                 en: 'Qatar',                    ar: 'قطر',                          de: 'Katar',                es: 'Catar',                it: 'Qatar',                pt: 'Catar',                ru: 'Катар',                tr: 'Katar',            id: 'Qatar',            ms: 'Qatar',            bn: 'কাতার',             ur: 'قطر',           ja: 'カタール',             ko: '카타르',         bm: 'Katari' },
  RO: { fr: 'Roumanie',              en: 'Romania',                  ar: 'رومانيا',                      de: 'Rumänien',             es: 'Rumanía',              it: 'Romania',              pt: 'Roménia',              ru: 'Румыния',              tr: 'Romanya',          id: 'Rumania',          ms: 'Romania',          bn: 'রোমানিয়া',          ur: 'رومانیہ',       ja: 'ルーマニア',           ko: '루마니아',       bm: 'Rumani' },
  GB: { fr: 'Royaume-Uni',           en: 'United Kingdom',           ar: 'المملكة المتحدة',              de: 'Vereinigtes Königreich', es: 'Reino Unido',         it: 'Regno Unito',          pt: 'Reino Unido',          ru: 'Великобритания',       tr: 'Birleşik Krallık', id: 'Inggris',         ms: 'United Kingdom',   bn: 'যুক্তরাজ্য',         ur: 'متحدہ مملکت',   ja: 'イギリス',             ko: '영국',           bm: 'Angletɛri' },
  RW: { fr: 'Rwanda',                en: 'Rwanda',                   ar: 'رواندا',                       de: 'Ruanda',               es: 'Ruanda',               it: 'Ruanda',               pt: 'Ruanda',               ru: 'Руанда',               tr: 'Ruanda',           id: 'Rwanda',           ms: 'Rwanda',           bn: 'রুয়ান্ডা',          ur: 'روانڈا',        ja: 'ルワンダ',             ko: '르완다',         bm: 'Ruwanda' },
  SN: { fr: 'Sénégal',               en: 'Senegal',                  ar: 'السنغال',                      de: 'Senegal',              es: 'Senegal',              it: 'Senegal',              pt: 'Senegal',              ru: 'Сенегал',              tr: 'Senegal',          id: 'Senegal',          ms: 'Senegal',          bn: 'সেনেগাল',           ur: 'سینیگل',        ja: 'セネガル',             ko: '세네갈',         bm: 'Senegali' },
  SL: { fr: 'Sierra Leone',          en: 'Sierra Leone',             ar: 'سيراليون',                     de: 'Sierra Leone',         es: 'Sierra Leona',         it: 'Sierra Leone',         pt: 'Serra Leoa',           ru: 'Сьерра-Леоне',         tr: 'Sierra Leone',     id: 'Sierra Leone',     ms: 'Sierra Leone',     bn: 'সিয়েরা লিওন',       ur: 'سیرالیون',      ja: 'シエラレオネ',         ko: '시에라리온',     bm: 'Siyɛra Leɔni' },
  SG: { fr: 'Singapour',             en: 'Singapore',                ar: 'سنغافورة',                     de: 'Singapur',             es: 'Singapur',             it: 'Singapore',            pt: 'Singapura',            ru: 'Сингапур',             tr: 'Singapur',         id: 'Singapura',        ms: 'Singapura',        bn: 'সিঙ্গাপুর',          ur: 'سنگاپور',       ja: 'シンガポール',         ko: '싱가포르',       bm: 'Singapuri' },
  SO: { fr: 'Somalie',               en: 'Somalia',                  ar: 'الصومال',                      de: 'Somalia',              es: 'Somalia',              it: 'Somalia',              pt: 'Somália',              ru: 'Сомали',               tr: 'Somali',           id: 'Somalia',          ms: 'Somalia',          bn: 'সোমালিয়া',          ur: 'صومالیہ',       ja: 'ソマリア',             ko: '소말리아',       bm: 'Somali' },
  SD: { fr: 'Soudan',                en: 'Sudan',                    ar: 'السودان',                      de: 'Sudan',                es: 'Sudán',                it: 'Sudan',                pt: 'Sudão',                ru: 'Судан',                tr: 'Sudan',            id: 'Sudan',            ms: 'Sudan',            bn: 'সুদান',             ur: 'سوڈان',         ja: 'スーダン',             ko: '수단',           bm: 'Sudani' },
  ZA: { fr: 'Afrique du Sud',        en: 'South Africa',             ar: 'جنوب أفريقيا',                 de: 'Südafrika',            es: 'Sudáfrica',            it: 'Sudafrica',            pt: 'África do Sul',        ru: 'ЮАР',                  tr: 'Güney Afrika',     id: 'Afrika Selatan',   ms: 'Afrika Selatan',   bn: 'দক্ষিণ আফ্রিকা',    ur: 'جنوبی افریقہ',  ja: '南アフリカ',           ko: '남아프리카',     bm: 'Afirik Worodugu' },
  SE: { fr: 'Suède',                 en: 'Sweden',                   ar: 'السويد',                       de: 'Schweden',             es: 'Suecia',               it: 'Svezia',               pt: 'Suécia',               ru: 'Швеция',               tr: 'İsveç',            id: 'Swedia',           ms: 'Sweden',           bn: 'সুইডেন',            ur: 'سویڈن',         ja: 'スウェーデン',         ko: '스웨덴',         bm: 'Suwɛdi' },
  CH: { fr: 'Suisse',                en: 'Switzerland',              ar: 'سويسرا',                       de: 'Schweiz',              es: 'Suiza',                it: 'Svizzera',             pt: 'Suíça',                ru: 'Швейцария',            tr: 'İsviçre',          id: 'Swiss',            ms: 'Switzerland',      bn: 'সুইজারল্যান্ড',      ur: 'سوئٹزرلینڈ',    ja: 'スイス',               ko: '스위스',         bm: 'Suwisi' },
  SY: { fr: 'Syrie',                 en: 'Syria',                    ar: 'سوريا',                        de: 'Syrien',               es: 'Siria',                it: 'Siria',                pt: 'Síria',                ru: 'Сирия',                tr: 'Suriye',           id: 'Suriah',           ms: 'Syria',            bn: 'সিরিয়া',           ur: 'شام',           ja: 'シリア',               ko: '시리아',         bm: 'Siri' },
  TJ: { fr: 'Tadjikistan',           en: 'Tajikistan',               ar: 'طاجيكستان',                    de: 'Tadschikistan',        es: 'Tayikistán',           it: 'Tagikistan',           pt: 'Tajiquistão',          ru: 'Таджикистан',          tr: 'Tacikistan',       id: 'Tajikistan',       ms: 'Tajikistan',       bn: 'তাজিকিস্তান',        ur: 'تاجکستان',      ja: 'タジキスタン',         ko: '타지키스탄',     bm: 'Tajikistani' },
  TZ: { fr: 'Tanzanie',              en: 'Tanzania',                 ar: 'تنزانيا',                      de: 'Tansania',             es: 'Tanzania',             it: 'Tanzania',             pt: 'Tanzânia',             ru: 'Танзания',             tr: 'Tanzanya',         id: 'Tanzania',         ms: 'Tanzania',         bn: 'তানজানিয়া',         ur: 'تنزانیہ',       ja: 'タンザニア',           ko: '탄자니아',       bm: 'Tanzani' },
  TD: { fr: 'Tchad',                 en: 'Chad',                     ar: 'تشاد',                         de: 'Tschad',               es: 'Chad',                 it: 'Ciad',                 pt: 'Chade',                ru: 'Чад',                  tr: 'Çad',              id: 'Chad',             ms: 'Chad',             bn: 'চাদ',               ur: 'چاڈ',           ja: 'チャド',               ko: '차드',           bm: 'Cadi' },
  TG: { fr: 'Togo',                  en: 'Togo',                     ar: 'توغو',                         de: 'Togo',                 es: 'Togo',                 it: 'Togo',                 pt: 'Togo',                 ru: 'Того',                 tr: 'Togo',             id: 'Togo',             ms: 'Togo',             bn: 'টোগো',              ur: 'ٹوگو',          ja: 'トーゴ',               ko: '토고',           bm: 'Togo' },
  TN: { fr: 'Tunisie',               en: 'Tunisia',                  ar: 'تونس',                         de: 'Tunesien',             es: 'Túnez',                it: 'Tunisia',              pt: 'Tunísia',              ru: 'Тунис',                tr: 'Tunus',            id: 'Tunisia',          ms: 'Tunisia',          bn: 'তিউনিসিয়া',         ur: 'تونس',          ja: 'チュニジア',           ko: '튀니지',         bm: 'Tunizi' },
  TM: { fr: 'Turkménistan',          en: 'Turkmenistan',             ar: 'تركمانستان',                   de: 'Turkmenistan',         es: 'Turkmenistán',         it: 'Turkmenistan',         pt: 'Turquemenistão',       ru: 'Туркменистан',         tr: 'Türkmenistan',     id: 'Turkmenistan',     ms: 'Turkmenistan',     bn: 'তুর্কমেনিস্তান',     ur: 'ترکمانستان',    ja: 'トルクメニスタン',     ko: '투르크메니스탄', bm: 'Turkmenistani' },
  TR: { fr: 'Turquie',               en: 'Turkey',                   ar: 'تركيا',                        de: 'Türkei',               es: 'Turquía',              it: 'Turchia',              pt: 'Turquia',              ru: 'Турция',               tr: 'Türkiye',          id: 'Turki',            ms: 'Turki',            bn: 'তুরস্ক',            ur: 'ترکیہ',         ja: 'トルコ',               ko: '터키',           bm: 'Turiki' },
  UG: { fr: 'Ouganda',               en: 'Uganda',                   ar: 'أوغندا',                       de: 'Uganda',               es: 'Uganda',               it: 'Uganda',               pt: 'Uganda',               ru: 'Уганда',               tr: 'Uganda',           id: 'Uganda',           ms: 'Uganda',           bn: 'উগান্ডা',           ur: 'یوگنڈا',        ja: 'ウガンダ',             ko: '우간다',         bm: 'Uganda' },
  UA: { fr: 'Ukraine',               en: 'Ukraine',                  ar: 'أوكرانيا',                     de: 'Ukraine',              es: 'Ucrania',              it: 'Ucraina',              pt: 'Ucrânia',              ru: 'Украина',              tr: 'Ukrayna',          id: 'Ukraina',          ms: 'Ukraine',          bn: 'ইউক্রেন',           ur: 'یوکرین',        ja: 'ウクライナ',           ko: '우크라이나',     bm: 'Ukɛrɛni' },
  UZ: { fr: 'Ouzbékistan',           en: 'Uzbekistan',               ar: 'أوزبكستان',                    de: 'Usbekistan',           es: 'Uzbekistán',           it: 'Uzbekistan',           pt: 'Uzbequistão',          ru: 'Узбекистан',           tr: 'Özbekistan',       id: 'Uzbekistan',       ms: 'Uzbekistan',       bn: 'উজবেকিস্তান',        ur: 'ازبکستان',      ja: 'ウズベキスタン',       ko: '우즈베키스탄',   bm: 'Uzbekistani' },
  YE: { fr: 'Yémen',                 en: 'Yemen',                    ar: 'اليمن',                        de: 'Jemen',                es: 'Yemen',                it: 'Yemen',                pt: 'Iémen',                ru: 'Йемен',                tr: 'Yemen',            id: 'Yaman',            ms: 'Yaman',            bn: 'ইয়েমেন',           ur: 'یمن',           ja: 'イエメン',             ko: '예멘',           bm: 'Yemɛni' },
  ZM: { fr: 'Zambie',                en: 'Zambia',                   ar: 'زامبيا',                       de: 'Sambia',               es: 'Zambia',               it: 'Zambia',               pt: 'Zâmbia',               ru: 'Замбия',               tr: 'Zambiya',          id: 'Zambia',           ms: 'Zambia',           bn: 'জাম্বিয়া',          ur: 'زامبیا',        ja: 'ザンビア',             ko: '잠비아',         bm: 'Zanbi' },
  ZW: { fr: 'Zimbabwe',              en: 'Zimbabwe',                 ar: 'زيمبابوي',                     de: 'Simbabwe',             es: 'Zimbabue',             it: 'Zimbabwe',             pt: 'Zimbabué',             ru: 'Зимбабве',             tr: 'Zimbabve',         id: 'Zimbabwe',         ms: 'Zimbabwe',         bn: 'জিম্বাবুয়ে',        ur: 'زمبابوے',       ja: 'ジンバブエ',           ko: '짐바브웨',       bm: 'Zimbabuwe' },
  US: { fr: 'États-Unis',            en: 'United States',            ar: 'الولايات المتحدة',             de: 'Vereinigte Staaten',   es: 'Estados Unidos',       it: 'Stati Uniti',          pt: 'Estados Unidos',       ru: 'США',                  tr: 'Amerika Birleşik Devletleri', id: 'Amerika Serikat', ms: 'Amerika Syarikat', bn: 'যুক্তরাষ্ট্র',      ur: 'ریاستہائے متحدہ', ja: 'アメリカ合衆国',     ko: '미국',           bm: 'Ameriki' },
  OM: { fr: 'Oman',                  en: 'Oman',                     ar: 'عُمان',                        de: 'Oman',                 es: 'Omán',                 it: 'Oman',                 pt: 'Omã',                  ru: 'Оман',                 tr: 'Umman',            id: 'Oman',             ms: 'Oman',             bn: 'ওমান',              ur: 'عمان',          ja: 'オマーン',             ko: '오만',           bm: 'Omani' },
  CN: { fr: 'Chine',                 en: 'China',                    ar: 'الصين',                        de: 'China',                es: 'China',                it: 'Cina',                 pt: 'China',                ru: 'Китай',                tr: 'Çin',              id: 'Tiongkok',         ms: 'China',            bn: 'চীন',               ur: 'چین',           ja: '中国',                 ko: '중국',           bm: 'Siniwali' },
  JP: { fr: 'Japon',                 en: 'Japan',                    ar: 'اليابان',                      de: 'Japan',                es: 'Japón',                it: 'Giappone',             pt: 'Japão',                ru: 'Япония',               tr: 'Japonya',          id: 'Jepang',           ms: 'Jepun',            bn: 'জাপান',             ur: 'جاپان',         ja: '日本',                 ko: '일본',           bm: 'Japɔni' },
  KR: { fr: 'Corée du Sud',          en: 'South Korea',              ar: 'كوريا الجنوبية',               de: 'Südkorea',             es: 'Corea del Sur',        it: 'Corea del Sud',        pt: 'Coreia do Sul',        ru: 'Южная Корея',          tr: 'Güney Kore',       id: 'Korea Selatan',    ms: 'Korea Selatan',    bn: 'দক্ষিণ কোরিয়া',    ur: 'جنوبی کوریا',   ja: '韓国',                 ko: '대한민국',       bm: 'Kore Worodugu' },
  TH: { fr: 'Thaïlande',             en: 'Thailand',                 ar: 'تايلاند',                      de: 'Thailand',             es: 'Tailandia',            it: 'Thailandia',           pt: 'Tailândia',            ru: 'Таиланд',              tr: 'Tayland',          id: 'Thailand',         ms: 'Thailand',         bn: 'থাইল্যান্ড',         ur: 'تھائی لینڈ',    ja: 'タイ',                 ko: '태국',           bm: 'Tayilandi' },
  VN: { fr: 'Vietnam',               en: 'Vietnam',                  ar: 'فيتنام',                       de: 'Vietnam',              es: 'Vietnam',              it: 'Vietnam',              pt: 'Vietname',             ru: 'Вьетнам',              tr: 'Vietnam',          id: 'Vietnam',          ms: 'Vietnam',          bn: 'ভিয়েতনাম',          ur: 'ویتنام',        ja: 'ベトナム',             ko: '베트남',         bm: 'Vyɛtinami' },
  AL: { fr: 'Albanie',               en: 'Albania',                  ar: 'ألبانيا',                      de: 'Albanien',             es: 'Albania',              it: 'Albania',              pt: 'Albânia',              ru: 'Албания',              tr: 'Arnavutluk',       id: 'Albania',          ms: 'Albania',          bn: 'আলবেনিয়া',          ur: 'البانیہ',       ja: 'アルバニア',           ko: '알바니아',       bm: 'Alibani' },
  AD: { fr: 'Andorre',               en: 'Andorra',                  ar: 'أندورا',                       de: 'Andorra',              es: 'Andorra',              it: 'Andorra',              pt: 'Andorra',              ru: 'Андорра',              tr: 'Andorra',          id: 'Andorra',          ms: 'Andorra',          bn: 'অ্যান্ডোরা',         ur: 'انڈورا',        ja: 'アンドラ',             ko: '안도라',         bm: 'Andɔra' },
  AM: { fr: 'Arménie',               en: 'Armenia',                  ar: 'أرمينيا',                      de: 'Armenien',             es: 'Armenia',              it: 'Armenia',              pt: 'Arménia',              ru: 'Армения',              tr: 'Ermenistan',       id: 'Armenia',          ms: 'Armenia',          bn: 'আর্মেনিয়া',         ur: 'آرمینیا',       ja: 'アルメニア',           ko: '아르메니아',     bm: 'Armeni' },
  BY: { fr: 'Biélorussie',           en: 'Belarus',                  ar: 'بيلاروس',                      de: 'Weißrussland',         es: 'Bielorrusia',          it: 'Bielorussia',          pt: 'Bielorrússia',         ru: 'Беларусь',             tr: 'Belarus',          id: 'Belarus',          ms: 'Belarus',          bn: 'বেলারুশ',           ur: 'بیلاروس',       ja: 'ベラルーシ',           ko: '벨라루스',       bm: 'Belarusi' },
  CY: { fr: 'Chypre',                en: 'Cyprus',                   ar: 'قبرص',                         de: 'Zypern',               es: 'Chipre',               it: 'Cipro',                pt: 'Chipre',               ru: 'Кипр',                 tr: 'Kıbrıs',           id: 'Siprus',           ms: 'Cyprus',           bn: 'সাইপ্রাস',           ur: 'قبرص',          ja: 'キプロス',             ko: '키프로스',       bm: 'Sipri' },
  HR: { fr: 'Croatie',               en: 'Croatia',                  ar: 'كرواتيا',                      de: 'Kroatien',             es: 'Croacia',              it: 'Croazia',              pt: 'Croácia',              ru: 'Хорватия',             tr: 'Hırvatistan',      id: 'Kroasia',          ms: 'Croatia',          bn: 'ক্রোয়েশিয়া',        ur: 'کروشیا',        ja: 'クロアチア',           ko: '크로아티아',     bm: 'Krowasi' },
  CZ: { fr: 'République tchèque',    en: 'Czech Republic',           ar: 'التشيك',                       de: 'Tschechien',           es: 'República Checa',      it: 'Repubblica Ceca',      pt: 'República Checa',      ru: 'Чехия',                tr: 'Çekya',            id: 'Ceko',             ms: 'Czech Republic',   bn: 'চেক প্রজাতন্ত্র',    ur: 'جمہوریہ چیک',   ja: 'チェコ',               ko: '체코',           bm: 'Cɛki' },
  EE: { fr: 'Estonie',               en: 'Estonia',                  ar: 'إستونيا',                      de: 'Estland',              es: 'Estonia',              it: 'Estonia',              pt: 'Estónia',              ru: 'Эстония',              tr: 'Estonya',          id: 'Estonia',          ms: 'Estonia',          bn: 'এস্তোনিয়া',         ur: 'ایسٹونیا',      ja: 'エストニア',           ko: '에스토니아',     bm: 'Ɛsitɔni' },
  GE: { fr: 'Géorgie',               en: 'Georgia',                  ar: 'جورجيا',                       de: 'Georgien',             es: 'Georgia',              it: 'Georgia',              pt: 'Geórgia',              ru: 'Грузия',               tr: 'Gürcistan',        id: 'Georgia',          ms: 'Georgia',          bn: 'জর্জিয়া',           ur: 'جارجیا',        ja: 'ジョージア',           ko: '조지아',         bm: 'Jorji' },
  HU: { fr: 'Hongrie',               en: 'Hungary',                  ar: 'هنغاريا',                      de: 'Ungarn',               es: 'Hungría',              it: 'Ungheria',             pt: 'Hungria',              ru: 'Венгрия',              tr: 'Macaristan',       id: 'Hungaria',         ms: 'Hungary',          bn: 'হাঙ্গেরি',           ur: 'ہنگری',         ja: 'ハンガリー',           ko: '헝가리',         bm: 'Ɔngri' },
  IS: { fr: 'Islande',               en: 'Iceland',                  ar: 'آيسلندا',                      de: 'Island',               es: 'Islandia',             it: 'Islanda',              pt: 'Islândia',             ru: 'Исландия',             tr: 'İzlanda',          id: 'Islandia',         ms: 'Iceland',          bn: 'আইসল্যান্ড',         ur: 'آئس لینڈ',      ja: 'アイスランド',         ko: '아이슬란드',     bm: 'Isiilandi' },
  XK: { fr: 'Kosovo',                en: 'Kosovo',                   ar: 'كوسوفو',                       de: 'Kosovo',               es: 'Kosovo',               it: 'Kosovo',               pt: 'Kosovo',               ru: 'Косово',               tr: 'Kosova',           id: 'Kosovo',           ms: 'Kosovo',           bn: 'কসোভো',             ur: 'کوسووو',        ja: 'コソボ',               ko: '코소보',         bm: 'Kosowo' },
  LV: { fr: 'Lettonie',              en: 'Latvia',                   ar: 'لاتفيا',                       de: 'Lettland',             es: 'Letonia',              it: 'Lettonia',             pt: 'Letónia',              ru: 'Латвия',               tr: 'Letonya',          id: 'Latvia',           ms: 'Latvia',           bn: 'লাতভিয়া',           ur: 'لٹویا',         ja: 'ラトビア',             ko: '라트비아',       bm: 'Letɔni' },
  LI: { fr: 'Liechtenstein',         en: 'Liechtenstein',            ar: 'ليختنشتاين',                   de: 'Liechtenstein',        es: 'Liechtenstein',        it: 'Liechtenstein',        pt: 'Liechtenstein',        ru: 'Лихтенштейн',          tr: 'Lihtenştayn',      id: 'Liechtenstein',    ms: 'Liechtenstein',    bn: 'লিশটেনস্টাইন',       ur: 'لیختنسٹائن',    ja: 'リヒテンシュタイン',   ko: '리히텐슈타인',   bm: 'Liyɛkitɛnsitayini' },
  LT: { fr: 'Lituanie',              en: 'Lithuania',                ar: 'ليتوانيا',                     de: 'Litauen',              es: 'Lituania',             it: 'Lituania',             pt: 'Lituânia',             ru: 'Литва',                tr: 'Litvanya',         id: 'Lituania',         ms: 'Lithuania',        bn: 'লিথুয়ানিয়া',        ur: 'لتھوانیا',      ja: 'リトアニア',           ko: '리투아니아',     bm: 'Lituani' },
  MT: { fr: 'Malte',                 en: 'Malta',                    ar: 'مالطا',                        de: 'Malta',                es: 'Malta',                it: 'Malta',                pt: 'Malta',                ru: 'Мальта',               tr: 'Malta',            id: 'Malta',            ms: 'Malta',            bn: 'মাল্টা',            ur: 'مالٹا',         ja: 'マルタ',               ko: '몰타',           bm: 'Maliti' },
  MC: { fr: 'Monaco',                en: 'Monaco',                   ar: 'موناكو',                       de: 'Monaco',               es: 'Mónaco',               it: 'Monaco',               pt: 'Mónaco',               ru: 'Монако',               tr: 'Monako',           id: 'Monako',           ms: 'Monaco',           bn: 'মোনাকো',            ur: 'موناکو',        ja: 'モナコ',               ko: '모나코',         bm: 'Monako' },
  ME: { fr: 'Monténégro',            en: 'Montenegro',               ar: 'الجبل الأسود',                 de: 'Montenegro',           es: 'Montenegro',           it: 'Montenegro',           pt: 'Montenegro',           ru: 'Черногория',           tr: 'Karadağ',          id: 'Montenegro',       ms: 'Montenegro',       bn: 'মন্টিনিগ্রো',        ur: 'مونٹینیگرو',    ja: 'モンテネグロ',         ko: '몬테네그로',     bm: 'Mɔntenɛguro' },
  RU: { fr: 'Russie',                en: 'Russia',                   ar: 'روسيا',                        de: 'Russland',             es: 'Rusia',                it: 'Russia',               pt: 'Rússia',               ru: 'Россия',               tr: 'Rusya',            id: 'Rusia',            ms: 'Rusia',            bn: 'রাশিয়া',           ur: 'روس',           ja: 'ロシア',               ko: '러시아',         bm: 'Rusi' },
  SM: { fr: 'Saint-Marin',           en: 'San Marino',               ar: 'سان مارينو',                   de: 'San Marino',           es: 'San Marino',           it: 'San Marino',           pt: 'São Marinho',          ru: 'Сан-Марино',           tr: 'San Marino',       id: 'San Marino',       ms: 'San Marino',       bn: 'সান মারিনো',         ur: 'سان مارینو',    ja: 'サンマリノ',           ko: '산마리노',       bm: 'San Marino' },
  RS: { fr: 'Serbie',                en: 'Serbia',                   ar: 'صربيا',                        de: 'Serbien',              es: 'Serbia',               it: 'Serbia',               pt: 'Sérvia',               ru: 'Сербия',               tr: 'Sırbistan',        id: 'Serbia',           ms: 'Serbia',           bn: 'সার্বিয়া',           ur: 'سربیا',         ja: 'セルビア',             ko: '세르비아',       bm: 'Sɛribi' },
  SK: { fr: 'Slovaquie',             en: 'Slovakia',                 ar: 'سلوفاكيا',                     de: 'Slowakei',             es: 'Eslovaquia',           it: 'Slovacchia',           pt: 'Eslováquia',           ru: 'Словакия',             tr: 'Slovakya',         id: 'Slovakia',         ms: 'Slovakia',         bn: 'স্লোভাকিয়া',        ur: 'سلوواکیہ',      ja: 'スロバキア',           ko: '슬로바키아',     bm: 'Silowaki' },
  SI: { fr: 'Slovénie',              en: 'Slovenia',                 ar: 'سلوفينيا',                     de: 'Slowenien',            es: 'Eslovenia',            it: 'Slovenia',             pt: 'Eslovénia',            ru: 'Словения',             tr: 'Slovenya',         id: 'Slovenia',         ms: 'Slovenia',         bn: 'স্লোভেনিয়া',        ur: 'سلووینیا',      ja: 'スロベニア',           ko: '슬로베니아',     bm: 'Siloweni' },
  VA: { fr: 'Vatican',               en: 'Vatican City',             ar: 'الفاتيكان',                    de: 'Vatikanstadt',         es: 'Ciudad del Vaticano',  it: 'Città del Vaticano',   pt: 'Cidade do Vaticano',   ru: 'Ватикан',              tr: 'Vatikan',          id: 'Vatikan',          ms: 'Vatican',          bn: 'ভ্যাটিকান',          ur: 'ویٹیکن',        ja: 'バチカン',             ko: '바티칸',         bm: 'Vatikani' },
  BN: { fr: 'Brunéi',                en: 'Brunei',                   ar: 'بروناي',                       de: 'Brunei',               es: 'Brunéi',               it: 'Brunei',               pt: 'Brunei',               ru: 'Бруней',               tr: 'Brunei',           id: 'Brunei',           ms: 'Brunei',           bn: 'ব্রুনাই',           ur: 'برونائی',       ja: 'ブルネイ',             ko: '브루나이',       bm: 'Brunɛyi' },
  BT: { fr: 'Bhoutan',               en: 'Bhutan',                   ar: 'بوتان',                        de: 'Bhutan',               es: 'Bután',                it: 'Bhutan',               pt: 'Butão',                ru: 'Бутан',                tr: 'Bhutan',           id: 'Bhutan',           ms: 'Bhutan',           bn: 'ভুটান',             ur: 'بھوٹان',        ja: 'ブータン',             ko: '부탄',           bm: 'Butani' },
  IL: { fr: 'Israël',                en: 'Israel',                   ar: 'إسرائيل',                      de: 'Israel',               es: 'Israel',               it: 'Israele',              pt: 'Israel',               ru: 'Израиль',              tr: 'İsrail',           id: 'Israel',           ms: 'Israel',           bn: 'ইসরায়েল',           ur: 'اسرائیل',       ja: 'イスラエル',           ko: '이스라엘',       bm: 'Izrayɛli' },
  KP: { fr: 'Corée du Nord',         en: 'North Korea',              ar: 'كوريا الشمالية',               de: 'Nordkorea',            es: 'Corea del Norte',      it: 'Corea del Nord',       pt: 'Coreia do Norte',      ru: 'Северная Корея',       tr: 'Kuzey Kore',       id: 'Korea Utara',      ms: 'Korea Utara',      bn: 'উত্তর কোরিয়া',      ur: 'شمالی کوریا',   ja: '北朝鮮',               ko: '북한',           bm: 'Kore Kɔrɔ' },
  LA: { fr: 'Laos',                  en: 'Laos',                     ar: 'لاوس',                         de: 'Laos',                 es: 'Laos',                 it: 'Laos',                 pt: 'Laos',                 ru: 'Лаос',                 tr: 'Laos',             id: 'Laos',             ms: 'Laos',             bn: 'লাওস',              ur: 'لاؤس',          ja: 'ラオス',               ko: '라오스',         bm: 'Lawosi' },
  LK: { fr: 'Sri Lanka',             en: 'Sri Lanka',                ar: 'سريلانكا',                     de: 'Sri Lanka',            es: 'Sri Lanka',            it: 'Sri Lanka',            pt: 'Sri Lança',            ru: 'Шри-Ланка',            tr: 'Sri Lanka',        id: 'Sri Lanka',        ms: 'Sri Lanka',        bn: 'শ্রীলঙ্কা',          ur: 'سری لنکا',      ja: 'スリランカ',           ko: '스리랑카',       bm: 'Siri Lanki' },
  MN: { fr: 'Mongolie',              en: 'Mongolia',                 ar: 'منغوليا',                      de: 'Mongolei',             es: 'Mongolia',             it: 'Mongolia',             pt: 'Mongólia',             ru: 'Монголия',             tr: 'Moğolistan',       id: 'Mongolia',         ms: 'Mongolia',         bn: 'মঙ্গোলিয়া',         ur: 'منگولیا',       ja: 'モンゴル',             ko: '몽골',           bm: 'Mɔngɔli' },
  MV: { fr: 'Maldives',              en: 'Maldives',                 ar: 'المالديف',                     de: 'Malediven',            es: 'Maldivas',             it: 'Maldive',              pt: 'Maldivas',             ru: 'Мальдивы',             tr: 'Maldivler',        id: 'Maladewa',         ms: 'Maldives',         bn: 'মালদ্বীপ',           ur: 'مالدیپ',        ja: 'モルディブ',           ko: '몰디브',         bm: 'Maldivi' },
  NP: { fr: 'Népal',                 en: 'Nepal',                    ar: 'نيبال',                        de: 'Nepal',                es: 'Nepal',                it: 'Nepal',                pt: 'Nepal',                ru: 'Непал',                tr: 'Nepal',            id: 'Nepal',            ms: 'Nepal',            bn: 'নেপাল',             ur: 'نیپال',         ja: 'ネパール',             ko: '네팔',           bm: 'Nepali' },
  TL: { fr: 'Timor oriental',        en: 'Timor-Leste',              ar: 'تيمور الشرقية',                de: 'Osttimor',             es: 'Timor Oriental',       it: 'Timor Est',            pt: 'Timor-Leste',          ru: 'Восточный Тимор',      tr: 'Doğu Timor',       id: 'Timor-Leste',      ms: 'Timor Timur',      bn: 'পূর্ব তিমুর',        ur: 'مشرقی تیمور',   ja: '東ティモール',         ko: '동티모르',       bm: 'Timɔri' },
  TW: { fr: 'Taïwan',                en: 'Taiwan',                   ar: 'تايوان',                       de: 'Taiwan',               es: 'Taiwán',               it: 'Taiwan',               pt: 'Taiwan',               ru: 'Тайвань',              tr: 'Tayvan',           id: 'Taiwan',           ms: 'Taiwan',           bn: 'তাইওয়ান',           ur: 'تائیوان',       ja: '台湾',                 ko: '대만',           bm: 'Tayiwani' },
  BW: { fr: 'Botswana',              en: 'Botswana',                 ar: 'بوتسوانا',                     de: 'Botswana',             es: 'Botsuana',             it: 'Botswana',             pt: 'Botsuana',             ru: 'Ботсвана',             tr: 'Botsvana',         id: 'Botswana',         ms: 'Botswana',         bn: 'বতসোয়ানা',          ur: 'بوٹسوانا',      ja: 'ボツワナ',             ko: '보츠와나',       bm: 'Botswana' },
  CV: { fr: 'Cap-Vert',              en: 'Cape Verde',               ar: 'الرأس الأخضر',                 de: 'Kap Verde',            es: 'Cabo Verde',           it: 'Capo Verde',           pt: 'Cabo Verde',           ru: 'Кабо-Верде',           tr: 'Cabo Verde',       id: 'Tanjung Verde',    ms: 'Cape Verde',       bn: 'কেপ ভার্দে',         ur: 'کیپ وردے',      ja: 'カーボベルデ',         ko: '카보베르데',     bm: 'Kap Vɛri' },
  ER: { fr: 'Érythrée',              en: 'Eritrea',                  ar: 'إريتريا',                      de: 'Eritrea',              es: 'Eritrea',              it: 'Eritrea',              pt: 'Eritreia',             ru: 'Эритрея',              tr: 'Eritre',           id: 'Eritrea',          ms: 'Eritrea',          bn: 'ইরিত্রিয়া',         ur: 'اریٹیریا',      ja: 'エリトリア',           ko: '에리트레아',     bm: 'Eritere' },
  SZ: { fr: 'Eswatini',              en: 'Eswatini',                 ar: 'إسواتيني',                     de: 'Eswatini',             es: 'Esuatini',             it: 'Eswatini',             pt: 'Essuatíni',            ru: 'Эсватини',             tr: 'Esvatini',         id: 'Eswatini',         ms: 'Eswatini',         bn: 'ইসোয়াতিনি',         ur: 'اسواتینی',      ja: 'エスワティニ',         ko: '에스와티니',     bm: 'Eswatini' },
  LS: { fr: 'Lesotho',               en: 'Lesotho',                  ar: 'ليسوتو',                       de: 'Lesotho',              es: 'Lesoto',               it: 'Lesotho',              pt: 'Lesoto',               ru: 'Лесото',               tr: 'Lesoto',           id: 'Lesotho',          ms: 'Lesotho',          bn: 'লেসোথো',            ur: 'لیسوتھو',       ja: 'レソト',               ko: '레소토',         bm: 'Lesoto' },
  LR: { fr: 'Libéria',               en: 'Liberia',                  ar: 'ليبيريا',                      de: 'Liberia',              es: 'Liberia',              it: 'Liberia',              pt: 'Libéria',              ru: 'Либерия',              tr: 'Liberya',          id: 'Liberia',          ms: 'Liberia',          bn: 'লাইবেরিয়া',         ur: 'لائبیریا',      ja: 'リベリア',             ko: '라이베리아',     bm: 'Liberiya' },
  MW: { fr: 'Malawi',                en: 'Malawi',                   ar: 'مالاوي',                       de: 'Malawi',               es: 'Malaui',               it: 'Malawi',               pt: 'Malawi',               ru: 'Малави',               tr: 'Malavi',           id: 'Malawi',           ms: 'Malawi',           bn: 'মালাউই',            ur: 'ملاوی',         ja: 'マラウイ',             ko: '말라위',         bm: 'Malawi' },
  MU: { fr: 'Maurice',               en: 'Mauritius',                ar: 'موريشيوس',                     de: 'Mauritius',            es: 'Mauricio',             it: 'Mauritius',            pt: 'Maurícia',             ru: 'Маврикий',             tr: 'Mauritius',        id: 'Mauritius',        ms: 'Mauritius',        bn: 'মরিশাস',            ur: 'ماریشس',        ja: 'モーリシャス',         ko: '모리셔스',       bm: 'Morisi' },
  SC: { fr: 'Seychelles',            en: 'Seychelles',               ar: 'سيشيل',                        de: 'Seychellen',           es: 'Seychelles',           it: 'Seychelles',           pt: 'Seicheles',            ru: 'Сейшелы',              tr: 'Seyşeller',        id: 'Seychelles',       ms: 'Seychelles',       bn: 'সেশেলস',            ur: 'سیچلس',         ja: 'セーシェル',           ko: '세이셸',         bm: 'Sɛsɛli' },
  SS: { fr: 'Soudan du Sud',         en: 'South Sudan',              ar: 'جنوب السودان',                 de: 'Südsudan',             es: 'Sudán del Sur',        it: 'Sudan del Sud',        pt: 'Sudão do Sul',         ru: 'Южный Судан',          tr: 'Güney Sudan',      id: 'Sudan Selatan',    ms: 'Sudan Selatan',    bn: 'দক্ষিণ সুদান',       ur: 'جنوبی سوڈان',   ja: '南スーダン',           ko: '남수단',         bm: 'Sudani Worodugu' },
  ST: { fr: 'Sao Tomé-et-Principe',  en: 'São Tomé and Príncipe',    ar: 'ساو تومي وبرينسيبي',           de: 'São Tomé und Príncipe', es: 'Santo Tomé y Príncipe', it: 'São Tomé e Príncipe', pt: 'São Tomé e Príncipe',  ru: 'Сан-Томе и Принсипи',  tr: 'São Tomé ve Príncipe', id: 'São Tomé dan Príncipe', ms: 'São Tomé dan Príncipe', bn: 'সাঁউ তুমি ও প্রিন্সিপি', ur: 'ساؤ ٹومے اور پرنسپے', ja: 'サントメ・プリンシペ', ko: '상투메 프린시페', bm: 'Sao Tome' },
  BR: { fr: 'Brésil',                en: 'Brazil',                   ar: 'البرازيل',                     de: 'Brasilien',            es: 'Brasil',               it: 'Brasile',              pt: 'Brasil',               ru: 'Бразилия',             tr: 'Brezilya',         id: 'Brasil',           ms: 'Brazil',           bn: 'ব্রাজিল',           ur: 'برازیل',        ja: 'ブラジル',             ko: '브라질',         bm: 'Berezili' },
  CO: { fr: 'Colombie',              en: 'Colombia',                 ar: 'كولومبيا',                     de: 'Kolumbien',            es: 'Colombia',             it: 'Colombia',             pt: 'Colômbia',             ru: 'Колумбия',             tr: 'Kolombiya',        id: 'Kolombia',         ms: 'Colombia',         bn: 'কলম্বিয়া',          ur: 'کولمبیا',       ja: 'コロンビア',           ko: '콜롬비아',       bm: 'Kolombi' },
  CL: { fr: 'Chili',                 en: 'Chile',                    ar: 'تشيلي',                        de: 'Chile',                es: 'Chile',                it: 'Cile',                 pt: 'Chile',                ru: 'Чили',                 tr: 'Şili',             id: 'Chili',            ms: 'Chile',            bn: 'চিলি',              ur: 'چلی',           ja: 'チリ',                 ko: '칠레',           bm: 'Sili' },
  PE: { fr: 'Pérou',                 en: 'Peru',                     ar: 'بيرو',                         de: 'Peru',                 es: 'Perú',                 it: 'Perù',                 pt: 'Peru',                 ru: 'Перу',                 tr: 'Peru',             id: 'Peru',             ms: 'Peru',             bn: 'পেরু',              ur: 'پیرو',          ja: 'ペルー',               ko: '페루',           bm: 'Peru' },
  VE: { fr: 'Venezuela',             en: 'Venezuela',                ar: 'فنزويلا',                      de: 'Venezuela',            es: 'Venezuela',            it: 'Venezuela',            pt: 'Venezuela',            ru: 'Венесуэла',            tr: 'Venezuela',        id: 'Venezuela',        ms: 'Venezuela',        bn: 'ভেনেজুয়েলা',        ur: 'وینزویلا',      ja: 'ベネズエラ',           ko: '베네수엘라',     bm: 'Venezuwela' },
};

/**
 * Returns the country name in the given locale ('fr-FR', 'en-US', 'ar-SA', …)
 * from the ISO 3166-1 alpha-2 code. Falls back to the code itself if unknown.
 */
export function getCountryName(isoCode, locale) {
  if (!isoCode) return null;
  const entry = NAMES[isoCode.toUpperCase()];
  if (!entry) return isoCode;
  const lang = (locale ?? 'fr').split('-')[0].split('_')[0];
  return entry[lang] ?? entry.fr ?? isoCode;
}

// Reverse map: normalized name (any language, lowercase) → ISO code
const NAME_TO_ISO = {};
for (const [iso, names] of Object.entries(NAMES)) {
  for (const name of Object.values(names)) {
    NAME_TO_ISO[name.toLowerCase()] = iso;
  }
}

/**
 * Returns true if `storedName` (as stored in DB, typically in French) matches
 * `query` in any supported language (fr, en, ar, de, es, it, pt, ru, tr, id, ms, bn, ur, ja, ko, bm).
 */
export function countryMatchesQuery(storedName, query) {
  if (!storedName || !query) return false;
  const q = query.toLowerCase().trim();
  const iso = NAME_TO_ISO[storedName.toLowerCase()];
  if (!iso) return storedName.toLowerCase().includes(q);
  return Object.values(NAMES[iso]).some(name => name.toLowerCase().includes(q));
}

// ISO country code → primary language(s) used in that country
const COUNTRY_LANG = {
  // Arabic
  DZ: ['ar', 'fr'], MA: ['ar', 'fr'], TN: ['ar', 'fr'], LY: ['ar'],
  EG: ['ar'], SA: ['ar'], IQ: ['ar'], SY: ['ar'], JO: ['ar'],
  LB: ['ar'], YE: ['ar'], OM: ['ar'], AE: ['ar'], KW: ['ar'],
  QA: ['ar'], BH: ['ar'], PS: ['ar'], SD: ['ar'], SS: ['ar'],
  SO: ['ar'], MR: ['ar'], KM: ['ar', 'fr'], DJ: ['ar', 'fr'],
  // French
  FR: ['fr'], SN: ['fr'], CI: ['fr'], ML: ['fr', 'bm'],
  GN: ['fr'], BF: ['fr'], CM: ['fr'], GA: ['fr'], CG: ['fr'],
  CD: ['fr'], TD: ['fr'], CF: ['fr'], BJ: ['fr'], TG: ['fr'],
  RW: ['fr'], MG: ['fr'], MU: ['fr'], SC: ['fr'],
  // English
  GB: ['en'], US: ['en'], AU: ['en'], NZ: ['en'],
  NG: ['en'], GH: ['en'], KE: ['en'], TZ: ['en'], UG: ['en'],
  ZA: ['en', 'af'], ZM: ['en'], ZW: ['en'], MW: ['en'],
  SL: ['en'], GM: ['en'], LR: ['en'], RW: ['en', 'fr'],
  // Bilingual / multilingual
  CA: ['fr', 'en'], BE: ['fr', 'nl', 'de'], CH: ['fr', 'de', 'it'],
  // Turkish
  TR: ['tr'],
  // German
  DE: ['de'], AT: ['de'], LI: ['de'],
  // Spanish
  ES: ['es'], MX: ['es'], AR: ['es'], CO: ['es'], PE: ['es'],
  VE: ['es'], CL: ['es'],
  // Portuguese
  BR: ['pt'], PT: ['pt'], MZ: ['pt'], AO: ['pt'], CV: ['pt'],
  // Russian
  RU: ['ru'], BY: ['ru'], KZ: ['ru', 'kk'], KG: ['ru'],
  // Italian
  IT: ['it'], SM: ['it'], VA: ['it'],
  // Dutch
  NL: ['nl'],
  // Indonesian / Malay
  ID: ['id'], MY: ['ms'], BN: ['ms'],
  // South Asian
  PK: ['ur'], BD: ['bn'], IN: ['hi', 'bn', 'ur', 'en'],
  // Japanese / Korean
  JP: ['ja'], KR: ['ko'],
};

/**
 * Returns true if the user's language matches the expected language(s) of
 * the country where the mosque is located.
 * When the country is unknown, always shows the comment (safe default).
 */
export function commentaireVisibleForLang(mosqueeIsoCode, userLang) {
  if (!mosqueeIsoCode) return true;
  const langs = COUNTRY_LANG[mosqueeIsoCode.toUpperCase()];
  if (!langs) return true;
  const lang = (userLang ?? 'fr').split('-')[0];
  return langs.includes(lang);
}
