// Shared mock janaza data — replaced by backend API responses when sagas are wired

export function createMockJanazas() {
  const now = Date.now();
  return [
    {
      id: '1',
      mosqueeId: 'm1',
      mosquee: 'Grande Mosquée de Paris',
      adresse: "2bis place du Puits de l'Ermite, Paris 5e",
      latitude: 48.8448,
      longitude: 2.3516,
      dateHeure: new Date(now + 3600000),
      statut: 'a_venir',
      genre: 'homme',
      nomDefunt: 'Ibrahim Al-Mansouri',
      estAnonyme: false,
      commentaire: 'Lavage à la salle Bilal à 13h00.',
      declarantEmail: 'test@example.com',
    },
    {
      id: '4',
      mosqueeId: 'm1',
      mosquee: 'Grande Mosquée de Paris',
      adresse: "2bis place du Puits de l'Ermite, Paris 5e",
      latitude: 48.8448,
      longitude: 2.3516,
      dateHeure: new Date(now + 5400000),
      statut: 'a_venir',
      genre: 'enfant',
      nomDefunt: '',
      estAnonyme: true,
      commentaire: 'Prière après Asr.',
      declarantEmail: 'admin@qabr.fr',
    },
    {
      id: '2',
      mosqueeId: 'm2',
      mosquee: 'Mosquée Omar',
      adresse: '53 rue Jean-Pierre Timbaud, Paris 11e',
      latitude: 48.8636,
      longitude: 2.3699,
      dateHeure: new Date(now + 7200000),
      statut: 'a_venir',
      genre: 'femme',
      nomDefunt: '',
      estAnonyme: true,
      commentaire: '',
      declarantEmail: 'autre@example.com',
    },
    {
      id: '3',
      mosqueeId: 'm3',
      mosquee: 'Mosquée Al-Fath',
      adresse: '5 rue Polonceau, Paris 18e',
      latitude: 48.8866,
      longitude: 2.3477,
      dateHeure: new Date(now - 1800000),
      statut: 'en_cours',
      genre: 'homme',
      nomDefunt: 'Youssef Benali',
      estAnonyme: false,
      commentaire: '',
      declarantEmail: 'user@qabr.fr',
    },
  ];
}
